872 adjust order of tokens in inspectannotate
six7/figma-tokens pull request #1007
Opened 2022-07-11 10:30 UTC by swordEdge

- [x] Functional review @six7

2022-07-12 01:13 UTC, LiamMartens requested changes

2022-07-12 01:13 UTC, LiamMartens commented on src/utils/convertToOrderObj.ts
> +import { Properties } from "@/constants/Properties";
Might be good to just write tests for these to get 100% coverage on those new utils

2022-07-12 01:13 UTC, LiamMartens commented on src/app/components/Initiator.tsx
>  import { StorageProviderType } from '@/constants/StorageProviderType';
Looks fine but can we get the coverage to be equal or more

2022-07-17 17:16 UTC, six7 commented
Functionality works 👍

2022-07-27 12:05 UTC, six7 approved these changes

2022-07-27 12:06 UTC, merged