854 UI crashing when entering reference pointing to typography token inside a different token type
six7/figma-tokens pull request #1014
Opened 2022-07-12 10:04 UTC by swordEdge

2022-07-13 02:46 UTC, LiamMartens requested changes

2022-07-13 02:46 UTC, LiamMartens commented on src/app/components/EditTokenForm.tsx
> +              <ResolvedValueDisplay value={resolvedValue} isColorToken={internalEditToken.type === 'color'} />
Can you use the `TokenTypes` enum; just for consistency

2022-07-13 02:46 UTC, LiamMartens commented on src/app/components/ResolvedValueDisplay.tsx
> +  value: string | number | TokenTypograpyValue | TokenBoxshadowValue | TokenBoxshadowValue[] | null;
If this is supposed to take any value - you can also use `SingleToken['value']`

2022-07-13 02:46 UTC, LiamMartens commented on src/app/components/ResolvedValueDisplay.tsx
> +    return <ResolvedShadowValueDisplay shadows={value as TokenBoxshadowValue[]} />;
Is the `as` necessary? I think due to the `isArray` type guard it should already resolve to be `TokenBoxshadowValue[]` since there are no other array types

2022-07-13 02:46 UTC, LiamMartens commented on src/app/components/ResolvedValueDisplay.tsx
> +  if (value && typeof value === 'object') {
Might be worth creating some generic type guard utilities in `utils/is`, similar to `isSingleTypographyToken`. Then you can also easily add coverage for those.

2022-07-13 02:46 UTC, LiamMartens commented on src/app/components/ResolvedValueDisplay.tsx
> +      <div className="flex p-2 mt-2 font-mono text-gray-700 bg-gray-100 border-gray-300 rounded text-xxs itms-center">
Are we able to update these to stitches since we're moving them now anyways - might as well rework them (if not too much work)

2022-07-13 11:21 UTC, swordEdge commented on src/app/components/ResolvedValueDisplay.tsx
> +      <div className="flex p-2 mt-2 font-mono text-gray-700 bg-gray-100 border-gray-300 rounded text-xxs itms-center">
I discussed this with Jan and right now it is decided that we just resolve the bug so that there is no more crash in the plugin.
https://brandcode-team.slack.com/archives/C03C1F17012/p1657708093676259

2022-07-14 18:15 UTC, LiamMartens approved these changes

2022-07-14 18:15 UTC, merged