584 after duplicating a token take user straight to the token edit form
six7/figma-tokens pull request #1047
Opened 2022-07-14 13:32 UTC by swordEdge

2022-07-17 16:53 UTC, six7 commented
@swordEdge this isn't working yet. The EditTokenForm pops up, which is as expected, but hitting `Duplicate` doesn't do anything.

2022-07-19 07:21 UTC, six7 commented
Functionality approved!

2022-07-21 01:50 UTC, LiamMartens requested changes

2022-07-21 01:50 UTC, LiamMartens commented on src/app/components/TokenTree.tsx
> +  status?: string;
Should this be typed as `EditTokenFormStatus` perhaps?

2022-07-21 01:50 UTC, LiamMartens commented on src/types/tokens/EditTokenObject.ts
> +  status: string;
Same here, this should probably be the enum you created.

2022-07-30 13:16 UTC, six7 approved these changes

2022-07-30 13:16 UTC, merged