869 improve error messages when connecting to a remote repository
six7/figma-tokens pull request #1076
Opened 2022-07-20 05:25 UTC by swordEdge

2022-07-21 06:08 UTC, six7 requested changes
I'd love it if we would also display `validation` errors, as in the contents failed to pass the validation checks we have in the various TokenStorage.ts files (e.g. in https://github.com/six7/figma-tokens/blob/32f8cdffe157812374059789000d8995b179848f/src/storage/FileTokenStorage.ts#L44) -> we should show the user then that their file contents don't pass the schema, e.g. `Contents don't pass schema validation`

2022-07-31 00:06 UTC, six7 requested changes
havent functionally tested this yet but went over the code

2022-07-31 00:06 UTC, six7 commented on src/storage/ADOTokenStorage.ts
>      } catch (e) {
should we return an errormessage as well when an error is caught?

2022-07-31 00:06 UTC, six7 commented on src/storage/RemoteTokenStorage.ts
> +    const content = await this.read();
should we keep `files` here? i feel it's easier to read + the singular is `file` later on as well

2022-07-31 00:06 UTC, six7 commented on src/storage/__tests__/GithubTokenStorage.test.ts
> +  // it('can read from Git in single file format', async () => {
i think we'll still want that test

2022-08-01 00:43 UTC, swordEdge commented on src/storage/ADOTokenStorage.ts
>      } catch (e) {
This is the case when the content failed validation schema

2022-08-01 00:43 UTC, swordEdge commented on src/storage/ADOTokenStorage.ts
>      } catch (e) {
This is the case when the content failed validation schema.

2022-08-02 03:09 UTC, LiamMartens approved these changes

2022-08-02 06:53 UTC, six7 approved these changes

2022-08-02 19:09 UTC, merged