feat: Startup logic
six7/figma-tokens pull request #1087
Opened 2022-07-25 03:11 UTC by LiamMartens

@six7 I streamlined the startup logic as I had mentioned before. Now the plugin data will be pre-fetched in one go and sent to the front-end where it will be handled in a single step-by-step process reducing the amount of round-trips and making the plugin logic more clear to reduce the possibility for errors.

I did alter the loading behavior of the plugin slightly where the initial pulling of the tokens will now also happen during the loading screen, but the loading screen has also been updated with more clear information for the user (clearly stating the different steps; such as verifying the license, getting the LD flags etc, ...).

The process now also ensures the LD flags are ready before initializing any other logic in the plugin ensuring the right features are available to the user at the right time.

2022-07-25 03:18 UTC, LiamMartens commented
https://user-images.githubusercontent.com/5265324/180692517-f7a59109-eedd-4ff7-a068-65ee9704abc8.mp4

2022-07-25 11:27 UTC, six7 commented
This is awesome, I love the various loading states! I tried with a couple different scenarios but will do some more testing and then look at the code. Thank you for this! 🎉

2022-07-29 03:23 UTC, LiamMartens commented
@six7 updated all the tests etc..

2022-07-30 23:52 UTC, six7 requested changes
haven't fully functionally tested yet but went through code and had just a few minor things to note. this is great, way more understandable!

2022-07-30 23:52 UTC, six7 commented on src/app/components/AppContainer/__tests__/AppContainerIntegration.test.tsx
> +    // useLDClientSpy.mockImplementation(() => ({
is this supposed to commented out?

2022-07-30 23:52 UTC, six7 commented on src/app/components/AppContainer/__tests__/AppContainerIntegration.test.tsx
> +    // useFlagsSpy.mockReset();
same, do we need those comments?

2022-07-30 23:52 UTC, six7 commented on src/app/components/AppContainer/startupProcessSteps/saveStorageInforamationFactory.ts
> +export function saveStorageInforamationFactory(
```suggestion
export function saveStorageInformationFactory(
```

should probably change any occurrence of this typo

2022-07-30 23:52 UTC, six7 commented on src/app/components/LaunchDarkly/LDProvider.tsx
> +  if (userId) {
just to confirm: was removing license key here intentional? i remember we limited this to just call launchdarkly when a license key was present to reduce the amount of API calls we need (as those have a plan limit)

2022-07-30 23:52 UTC, six7 commented on src/utils/uiSettings.ts
> +    console.error(err);
just so i understand: when should we use `handleReactError` and when just a console err? It feels like we'd always want `handleReactError` as we can then track these?

2022-07-31 00:28 UTC, six7 commented
One thing I noticed: If there's a credentials error during startup the plugin stays in `Fetching credentials` loading state forever. This happened with ADO sync.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/4548309/182004573-a384ece6-2867-46d3-a49d-3f908afc3465.png">

2022-07-31 13:01 UTC, LiamMartens commented on src/utils/uiSettings.ts
> +    console.error(err);
The `uiSettings.ts` file is used on the plugin side - not the react side; we can't really track much on the plugin side due to the sandboxing - so `handleReactError` should only be used in the UI side

2022-07-31 13:09 UTC, LiamMartens commented on src/app/components/LaunchDarkly/LDProvider.tsx
> +  if (userId) {
Ahh I see - I'll re-add it and add a comment in code

2022-07-31 15:40 UTC, LiamMartens commented
@six7 the error occurs if the local api credentials are invalid or something?

2022-08-01 02:10 UTC, LiamMartens commented
@six7 issue with the loading state should be fixed

2022-08-02 06:58 UTC, six7 approved these changes

2022-08-02 06:58 UTC, six7 commented
Can you resolve merge conflicts? After that let's merge this in.

2022-08-04 03:35 UTC, merged