add expandComposition
six7/figma-tokens pull request #1110
Opened 2022-08-03 10:18 UTC by swordEdge

2022-08-04 16:32 UTC, six7 requested changes
Could you also add a few composition tokens in the https://github.com/six7/figma-tokens/tree/main/token-transformer/tokens files and make sure that we test that from a token-transformer level? 

The "tests" there are basically running token-transformer with a few inputs that should then produce certain outputs: https://github.com/six7/figma-tokens/blob/main/token-transformer/package.json

2022-08-08 02:56 UTC, LiamMartens approved these changes

2022-08-09 06:44 UTC, six7 requested changes
Can you add a test for this in `token-transformer/transform.test.js`? You'll need to add a `output/composition.json` so the test know what is the expected result, you can look at the other tests to see how that was done.

2022-08-09 06:49 UTC, six7 commented on token-transformer/package.json
> +    "build-composition-test": "node index.js tokens.json temp/composition.json base/options,base/sizing,core/composition base/options,base/sizing",
```suggestion
    "build-composition-test": "node index.js tokens.json temp/composition.json base/options,base/sizing,core/composition base/options,base/sizing --expandComposition=true",
```

2022-08-09 06:49 UTC, six7 commented on token-transformer/package.json
> +    "build-composition-test": "node index.js tokens.json temp/composition.json base/options,base/sizing,core/composition base/options,base/sizing",
this needs to be enabled to be run

2022-08-11 06:24 UTC, six7 approved these changes

2022-08-11 06:24 UTC, merged