add ability-collapse-expand-token
six7/figma-tokens pull request #1111
Opened 2022-08-03 12:25 UTC by MightyDevKnight

2022-08-03 17:55 UTC, six7 commented
Can you add test coverage for this new functionality?

2022-08-06 15:19 UTC, LiamMartens requested changes

2022-08-06 15:19 UTC, LiamMartens commented on src/app/components/TokenTree.tsx
> +                    <svg width="6" height="6" viewBox="0 0 6 6" xmlns="http://www.w3.org/2000/svg">
Should these be moved to svg files?

2022-08-19 06:43 UTC, six7 requested changes
some minor comments, otherwise this is good!

2022-08-19 06:43 UTC, six7 commented on src/app/components/TokenTree.test.tsx
> +  it('should be able to collpase token tree', async () => {
```suggestion
  it('should be able to collapse a token group', async () => {
```

2022-08-19 06:43 UTC, six7 commented on src/app/components/TokenTree.test.tsx
> +  it('should be able to expand token tree', async () => {
```suggestion
  it('should be able to expand a token group', async () => {
```

2022-08-19 06:43 UTC, six7 commented on src/app/components/TokenTree.test.tsx
> +  it('should be able to work add a new token', async () => {
```suggestion
  it('should be able to add a new token', async () => {
```

2022-08-19 06:43 UTC, six7 commented on src/app/components/TokenTree.tsx
> +const StyledCollapsableTokenGroupHeadingButton = styled('button', {
can we move this to its own file? same with the StyledTokenGroup above? That way this file doesnt contain styling

2022-08-22 21:14 UTC, six7 approved these changes

2022-08-22 21:15 UTC, merged