fix: typescript error
six7/figma-tokens pull request #1118
Opened 2022-08-04 12:49 UTC by swordEdge

2022-08-06 15:20 UTC, LiamMartens requested changes

2022-08-06 15:20 UTC, LiamMartens commented on src/storage/GithubTokenStorage.ts
> +        let treeResponse;
I see quite a lot has changed here - what was the actual fix?

2022-08-08 02:35 UTC, swordEdge commented on src/storage/GithubTokenStorage.ts
> +        let treeResponse;
On organization github account, users are not allowed to create a tree with read-only permission.
And in the current logic, we create a tree object to get contents in the directory recursively.
That's why this issue happening.
So I changed the logic where we get a tree object not creating that one when creating a tree object failed.

2022-08-08 02:54 UTC, LiamMartens commented on src/storage/GithubTokenStorage.ts
> +        let treeResponse;
I see - so does the reading of the entire directory still work then with read-only permission? And if it does then can we cut out creating a tree altogether?

2022-08-08 15:07 UTC, swordEdge commented on src/storage/GithubTokenStorage.ts
> +        let treeResponse;
Yes. reading of the entire directory still workwith read-only permission.
Yes. we can cut out creating a tree altogether

2022-08-08 21:09 UTC, LiamMartens commented on src/storage/GithubTokenStorage.ts
> +        let treeResponse;
@six7 should we then cut out the `createTree` step here altogether? I assume it will make it faster since it takes out a API call.

2022-08-08 21:21 UTC, six7 commented on src/storage/GithubTokenStorage.ts
> +        let treeResponse;
Lets remove it then 👍

2022-08-09 09:54 UTC, swordEdge commented on src/storage/GithubTokenStorage.ts
> +        let treeResponse;
@six7 @LiamMartens  Removed the createTree step.

2022-08-10 02:46 UTC, LiamMartens approved these changes

2022-08-10 06:27 UTC, six7 requested changes
This currently fails when the filePath is set to a nested directory that didn't exist yet:

To reproduce:
- Go to sync settings of GitHub
- Change filePath to `some/random/path/that/doesntexist` (or anything else that is nested
- When the plugin asks you to push, you push

Notice that there's an error.

2022-08-10 16:36 UTC, six7 approved these changes

2022-08-10 16:36 UTC, merged