Add boxShadow Fixes #29
six7/figma-tokens pull request #112
Opened 2021-04-17 02:28 UTC by scttdavs

Thanks for this plugin! Our team is starting to use it and is really excited about it. The one thing it is missing from what we'd like is just a box-shadow token. So here is my shot at it 😀 Let me know if I've missing anything. I'm open to naming also, just went with boxShadow for now.

![image](https://user-images.githubusercontent.com/3631216/115098857-6d72f980-9f00-11eb-89fa-cc3234b07952.png)

2021-04-17 02:31 UTC, scttdavs commented on src/config/tokens.js
> +    boxShadow: ['boxShadow'],
I'm not exactly sure what this file is for, but I think I probably did this wrong.

2021-04-18 10:33 UTC, six7 requested changes
Awesome work @scttdavs ! Thanks for this.

Some things that I'm still unsure of, but I think we can solve these in another issue:
- Would it make sense to allow entering box-shadows in a css-like syntax? e.g. `0 0 4px -4px rgba(0,0,0,0.5)`? I really like that users are able to enter different values for each property. And if we're looking to be conform with style dictionary I think that can be solved by a transformer later.
- I think it would be great if users could create and update effect styles from within the plugin, similar to how we do it for color and typography tokens. I realize this is a bigger effort (as we don't have effect style tokens yet) so I'd be fine with moving that functionality to it's own issue.

Once you resolved the two comments I'd say we'd be good to go! 🎉

2021-04-18 10:33 UTC, six7 commented on src/plugin/updateNode.ts
> +            effects.push(effect);
I'd rather replace the whole effects array with the new effect. Because right now this leads to a bug: any time someone updates tokens, a new boxShadow effect is pushed to all tokens that contain a reference to this token.

2021-04-18 10:33 UTC, six7 commented on src/config/default.json
> +    },
This will lead to the UI showing 4 different tokens (the plugin basically checks for a `value` prop in a token, if it finds that, it is understood to be a single token rather than multiple). An exception are typography tokens, which have some logic involved due to wanting to support old no-value tokens. But I'd say for new tokens like `boxShadow` we can force the new syntax.

So, adding the `value` prop will make sure that the token is displayed as a single token.

```suggestion
    "boxShadow": {
        "dark": {
          "value": {
            "x": 5,
            "y": 5,
            "spread": 3,
            "color": "rgba(0, 0, 0, 0.5)",
            "blur": 5
          }
        }
    },
```

2021-04-18 10:33 UTC, six7 commented on src/config/tokens.js
> +    boxShadow: ['boxShadow'],
You're right, this file is not needed anymore (the properties file is need to tell the plugin what keys to look at). Will remove in a future update.

2021-04-19 15:28 UTC, scttdavs commented on src/plugin/updateNode.ts
> +            effects.push(effect);
good catch! I filtered out the `DROP_SHADOW` effect instead, that way any other effects that happen to be applied will not be lost. Seemed a little safer that way.

2021-04-19 15:31 UTC, scttdavs commented
> Would it make sense to allow entering box-shadows in a css-like syntax? e.g. 0 0 4px -4px rgba(0,0,0,0.5)? I really like that users are able to enter different values for each property. And if we're looking to be conform with style dictionary I think that can be solved by a transformer later.
I think it would be great if users could create and update effect styles from within the plugin, similar to how we do it for color and typography tokens. I realize this is a bigger effort (as we don't have effect style tokens yet) so I'd be fine with moving that functionality to it's own issue.

Hmm, yes, I thought about the css-like declaration, but thought it may be too code-like for some designers, and thought keeping the Figma language and inputs that they would be used to would be simpler. I agree, that other one sounds like it could be a good improvement for a separate ticket. This PR would at least open things up and allow folks to start using boxShadows :D

2021-04-19 15:32 UTC, scttdavs commented on src/config/default.json
> +    },
👍 another good catch!

2021-04-20 07:46 UTC, six7 approved these changes
Awesome, thank you for your contribution 🙏

2021-04-20 07:46 UTC, six7 commented
Will merge this and include it in the next version 👍

2021-04-20 07:46 UTC, merged

2021-04-21 07:58 UTC, six7 commented
version 51 just got released with boxShadow support!