fix: URL amd JSONbin storage
six7/figma-tokens pull request #1172
Opened 2022-08-16 03:15 UTC by LiamMartens

Updated URL storage provider to support themes and metadata
Updated JSONbin to support metadata

Fixes #1164 

@six7 I did notice JSONBin currently always asks to recover local changes (also in the live plugin), We may want to review this behavior - but it's a bit of a weird one because it's the only provider type we automatically sync as opposed to the git providers. Perhaps there is merit in just aligning the logic altogether and also making this a manual action like the git providers?

2022-08-16 03:15 UTC, LiamMartens commented
@six7 I did notice JSONBin currently always asks to recover local changes (also in the live plugin), We may want to review this behavior - but it's a bit of a weird one because it's the only provider type we automatically sync as opposed to the git providers. Perhaps there is merit in just aligning the logic altogether and also making this a manual action like the git providers?

2022-08-17 07:03 UTC, six7 requested changes
## Two `version` and `updatedAt` placements
We now have 2 places where we track updatedAt and version, is this intended? I really like placing it in metadata fwiw!

<img width="491" alt="image" src="https://user-images.githubusercontent.com/4548309/185054872-c0fd7618-43b4-4b6c-bfa1-145f16a11424.png">

<img width="415" alt="image" src="https://user-images.githubusercontent.com/4548309/185054914-3db63a10-8766-441a-b602-675564520c27.png">

Other than that this works as intended 🙏  Would love to know the thoughts behind the two version and updatedAt placements

2022-08-17 07:18 UTC, six7 commented
> @six7 I did notice JSONBin currently always asks to recover local changes (also in the live plugin), We may want to review this behavior - but it's a bit of a weird one because it's the only provider type we automatically sync as opposed to the git providers. Perhaps there is merit in just aligning the logic altogether and also making this a manual action like the git providers?

Yeah agree, we should align as much as we can, making this a manual pull/push action would be great. I'll create an issue

2022-08-23 21:36 UTC, six7 approved these changes

2022-08-23 21:36 UTC, merged