1155 export doesnt include metadata or themes
six7/figma-tokens pull request #1178
Opened 2022-08-16 15:19 UTC by swordEdge

2022-08-16 20:39 UTC, LiamMartens approved these changes

2022-08-17 06:39 UTC, six7 requested changes
Few things that dont work:

- When we are exporting a **single token set** we don't want $themes or $metadata to be included (Both with "Include parent keys" and without that)
- Importing a .json file that was exported with $metadata shows $metadata as a token set, which it shouldn't.
<img width="153" alt="image" src="https://user-images.githubusercontent.com/4548309/185051495-dd1902f5-8e27-498e-8b4d-578908b2294b.png">

2022-08-17 06:39 UTC, six7 commented on src/app/store/remoteTokens.tsx
> +        const sortedTokens = applyTokenSetOrder(remoteData.tokens, remoteData.metadata?.tokenSetOrder ?? []);
```suggestion
        const sortedTokens = applyTokenSetOrder(remoteData.tokens, remoteData.metadata?.tokenSetOrder ?? Object.keys(remoteData.tokens);
```

If no metadata is present we should respect the order of the token sets in the JSON

2022-08-19 06:51 UTC, six7 approved these changes

2022-08-19 06:51 UTC, merged