807 cannot set a number fontweight in typography
six7/figma-tokens pull request #1197
Opened 2022-08-19 09:09 UTC by swordEdge

2022-08-19 13:23 UTC, LiamMartens requested changes

2022-08-19 13:23 UTC, LiamMartens commented on src/plugin/setValuesOnNode.ts
> +  console.log('values', values);
logs

2022-08-19 15:49 UTC, six7 requested changes

2022-08-19 15:49 UTC, six7 commented on src/plugin/setTextValuesOnTarget.ts
> +      const transformedValue = transformValue(style, 'fontWeights');
Can we change this so we 
1) First try to set font weight as it is
2) If that fails try the mapping

Reason is that some (not a lot) fonts have weights actually named '500'

2022-08-19 18:12 UTC, six7 commented
This works great so far!

One more thing that I feel would be really great if we could get in, as that way we'd probably be able to cover a lot more font weights

Some fonts define their weights not like `SemiBold` but `Semi Bold` (notice the space between Semi and Bold), or sometimes even `DemiBold`.

Could we pass in our mapping an array of possible weight names? Then we could extend that with some mappings that map in certain font weights. We'd then try to set each of them, and if there's a match, it will apply that?

In the case of `600` this would mean we'd return `['SemiBold', 'Semi Bold', 'DemiBold']`? We could use an array for each of these, as I'm sure we'd need to add more possible variations to the other weights later?

2022-08-23 06:59 UTC, six7 requested changes
Nice! some minor comments

2022-08-23 06:59 UTC, six7 commented on src/plugin/setTextValuesOnTarget.test.ts
> +  it(`can't set number fontWeight to the node if there is no match fontWeight`, async () => {
```suggestion
  it(`can't set number fontWeight to the node if there is no matching fontWeight`, async () => {
```

2022-08-23 06:59 UTC, six7 commented on src/plugin/setTextValuesOnTarget.test.ts
> +  it('convert number fontWeight and sets to the node', async () => {
```suggestion
  it('converts a numerical fontWeight and sets to the node', async () => {
```

2022-08-23 06:59 UTC, six7 commented on src/plugin/setTextValuesOnTarget.ts
> +        await figma.loadFontAsync({ family, style });
can we move the await inside the `if (fontFamily || fontWeight)`? Then it will only run if required

2022-08-23 06:59 UTC, six7 commented on src/plugin/setTextValuesOnTarget.ts
> +                if (fontFamily || fontWeight) {
i think we don't even need this check? if we do, it should check for `family` and `candidateStyle` - as these are the properties we're setting here.

2022-08-24 06:01 UTC, six7 requested changes
Small change + can we get test coverage to pass?

2022-08-24 06:01 UTC, six7 commented on src/plugin/setTextValuesOnTarget.ts
> +                if (fontFamily || candidateStyle) {
We dont need to check for fontFamily here as we're in an if condition that already checks for that on line 23.

So can just be a check for candidateStyle?

2022-08-26 16:49 UTC, LiamMartens approved these changes

2022-08-30 22:01 UTC, six7 commented
Can we still get the test coverage to pass @swordEdge ? Then I'd merge this in 👍

2022-09-01 21:34 UTC, six7 approved these changes

2022-09-01 21:34 UTC, merged

2022-09-21 18:55 UTC, jsamr commented
@six7 Sorry to bother you! Has this fix been included in version 119?

2022-09-22 19:00 UTC, six7 commented
We released this today with version 120 👍