save current update mode
six7/figma-tokens pull request #1211
Opened 2022-08-22 23:38 UTC by swordEdge

2022-08-23 09:37 UTC, LiamMartens commented
@six7 do we also need to remember this on the file or client ?

2022-08-23 21:40 UTC, six7 commented
> @six7 do we also need to remember this on the file or client ?

Probably later on the client but let's see if the current solution satisfies that already.

2022-08-23 21:51 UTC, six7 requested changes
Let's also store this decision on the client (not file, but client). After testing it felt weird that it would always go back to another choice after restarting the plugin. Users will probably want to set this once, and then keep.

2022-08-23 21:51 UTC, six7 commented on src/app/store/models/uiState.tsx
> +    currentUpdateMode: UpdateMode.DOCUMENT,
can we change that back to `PAGE`? Document is something that takes a long time for some users so I'd rather keep the default to something that doesn't take minutes to complete

2022-08-26 16:50 UTC, LiamMartens approved these changes

2022-08-26 22:03 UTC, merged