1195 when deleting a token ask to delete any local styles
six7/figma-tokens pull request #1242
Opened 2022-09-01 10:31 UTC by swordEdge

2022-09-01 12:19 UTC, LiamMartens requested changes

2022-09-01 12:19 UTC, LiamMartens commented on src/utils/is/isMatchingStyle.ts
> +export function isMatchingStyle(style: PaintStyle | TextStyle | EffectStyle, token: DeleteTokenPayload) {
There is a util called `convertTokenNameToPath` which could be used here instead. Perhaps in combination with `matchStyleName`. See `setValuesOnNode.ts` line `80` for an example

2022-09-01 12:19 UTC, LiamMartens commented on src/app/store/useTokens.tsx
> +    // dispatch.tokenState.assignStyleIdsToCurrentTheme(createStylesResult.styleIds);
We should probably implement the logic to also remove the token from the theme styles.

2022-09-04 03:36 UTC, LiamMartens requested changes

2022-09-04 03:36 UTC, LiamMartens commented on src/app/store/models/reducers/tokenState/removeStyleIdsFromCurrentTheme.ts
> +  const tokenToRemove = Object.keys(styleIds)[0];
I'm wondering if this should support the removal of multiple tokens? The interface kind of makes this a confusing behavior if it only picks the first one

2022-09-04 15:55 UTC, six7 commented on src/app/store/models/reducers/tokenState/removeStyleIdsFromCurrentTheme.ts
> +  const tokenToRemove = Object.keys(styleIds)[0];
Yeah let's support deleting multiple. It could be users have multiple tokens created that are actually named the same, so lets just iterate over all of them to delete them?

2022-09-06 22:03 UTC, six7 requested changes

2022-09-06 22:03 UTC, six7 commented on src/app/store/useManageTokens.test.tsx
> +  it('should be able to remove styles from the currentTheme when the user select option', async () => {
Should be able to remove styles from any theme if the user deleted one

2022-09-06 22:03 UTC, six7 commented on src/plugin/removeStylesFromPlugin.ts
> +      style.remove();
In here we'd also need to pass back that styleId so we can delete those connected figmaStyleReferenced

2022-09-08 19:53 UTC, six7 requested changes
This does not work yet.. it deletes all styles instead of deleting just the style that should be deleted. happens both when themes are present and when they're not present

https://user-images.githubusercontent.com/4548309/189213577-19342687-d69e-483f-b562-1f3f998e60a9.mp4



could you make sure to include a short video in the PRs once they're ready for review? then we could give feedback like that quicker 🙏

2022-09-09 17:29 UTC, swordEdge commented
> This does not work yet.. it deletes all styles instead of deleting just the style that should be deleted. happens both when themes are present and when they're not present
> 
>  CleanShot.2022-09-08.at.21.50.03.mp4 
> could you make sure to include a short video in the PRs once they're ready for review? then we could give feedback like that quicker 🙏


@six7  Checkout this video. 
https://www.loom.com/share/6fb659e27cd8446c925fbd38eb7bc940

2022-09-15 13:23 UTC, LiamMartens commented
@swordEdge what is the current status here?

2022-09-21 06:52 UTC, swordEdge commented
@swordEdge Hi.

2022-09-26 03:33 UTC, LiamMartens approved these changes

2022-09-26 08:10 UTC, merged