1194 when renaming a token ask to rename any local styles in addition to the remap tokens functionality we have
six7/figma-tokens pull request #1243
Opened 2022-09-02 11:39 UTC by swordEdge

When we currently rename a token, we can update the styles in the document and activeTheme either.

2022-09-04 03:36 UTC, LiamMartens commented
Also coverage :grimacing:

2022-09-06 22:05 UTC, six7 requested changes

2022-09-06 22:05 UTC, six7 commented on src/app/store/models/reducers/tokenState/renameStyleIdsToCurrentTheme.ts
> +  if (!state.activeTheme) return state;
For this PR the same feedback as for the other: it could be the user doesnt have that theme open but deletes a token - which deletes a style - that might be connected to a figmaStyleReference of an inactive theme

2022-09-08 05:43 UTC, swordEdge commented on src/app/store/models/reducers/tokenState/renameStyleIdsToCurrentTheme.ts
> +  if (!state.activeTheme) return state;
@six7 I'll complete this pr after 1195 has been merged.

2022-09-08 14:07 UTC, LiamMartens approved these changes

2022-09-08 14:07 UTC, LiamMartens commented on src/app/store/models/reducers/__tests__/renameStyleIdsToTheme.test.ts
> +    store = init<RootModel>({
btw you can use `createMockStore` instead

2022-09-29 03:10 UTC, LiamMartens commented
@swordEdge could you solve the conflicts?

2022-09-29 19:18 UTC, merged