bug fix
six7/figma-tokens pull request #1280
Opened 2022-09-13 07:58 UTC by swordEdge

Sometimes when using Git storage removing a token set fails. It seems to be connected to the name of the set, as it's not happening all the time.

2022-09-13 12:00 UTC, LiamMartens approved these changes

2022-09-15 19:32 UTC, six7 requested changes
This seems to be removing files that I did not remove.

In this commit I only deleted the file `Colors/Archive.json` - but `Base/Colors/Archive.json` was deleted as well.

Can we add tests for this please?

2022-09-16 00:54 UTC, swordEdge commented
> In this commit I only deleted the file `Colors/Archive.json` - but `Base/Colors/Archive.json` was deleted as well.
@six7 In my computer it works properly. Could you check this video and again in your computer.
https://www.loom.com/share/a383c5d6b04e42b1aede02bd60f91846

2022-09-17 21:29 UTC, six7 commented
Great, works now! Merging in

2022-09-17 21:30 UTC, merged