1293 changes to license key display
six7/figma-tokens pull request #1331
Opened 2022-10-09 19:17 UTC by MightyDevKnight

![ScreenShot_20221010041445](https://user-images.githubusercontent.com/102773603/194775462-426a5a1d-ddfd-4cb7-a6e1-03ab811d6c66.jpeg)

2022-10-10 00:48 UTC, LiamMartens approved these changes
@MightyDevKnight let's just get the coverage

2022-10-11 18:20 UTC, six7 requested changes

2022-10-11 18:20 UTC, six7 commented on src/app/components/AddLicenseKey/AddLicenseKey.tsx
> +          <ManageSubscriptionLink href="https://docs.figmatokens.com/" target="_blank">
the correct link is https://account.figmatokens.com/

2022-10-13 06:54 UTC, six7 commented on src/app/components/AddLicenseKey/AddLicenseKey.tsx
> +          <ManageSubscriptionLink href="https://docs.figmatokens.com/" target="_blank">
```suggestion
          <ManageSubscriptionLink href="https://account.figmatokens.com/" target="_blank">
```

2022-10-13 06:55 UTC, merged