1265 add support for asset tokens
six7/figma-tokens pull request #1337
Opened 2022-10-11 23:13 UTC by swordEdge

https://www.loom.com/share/831546f59ed641f592826eab3cf62d2a

2022-10-12 00:37 UTC, swordEdge commented on src/plugin/setValuesOnNode.ts
> +          const newPaint = await fetch(imageUrl).then((response) => response.arrayBuffer());
It works. I'll suggest the related information if I find.

2022-10-12 03:28 UTC, LiamMartens requested changes
@six7 I'm wondering a little bit here what the actual behavior should be as to the combination of styles and assets. We can't really match on anything to find an existing style because the byte objects will always be different and the paint will have no reference as to what the image source is. I think we will just need to forego any style matching here because we can't check the equality of values

2022-10-12 03:28 UTC, LiamMartens commented on src/plugin/figmaUtils/styleMatchers/paintStyleMatchesImageToken.ts
> +      return bytes === imageArrayBuffer;
I believe this will always return `false` since 2 objects created from different sources can never be identical. This would require a byte per byte comparison I think which - in my opinion - is not worth the performance trade off 

FYI @six7

2022-10-12 05:42 UTC, six7 commented
> @six7 I'm wondering a little bit here what the actual behavior should be as to the combination of styles and assets. We can't really match on anything to find an existing style because the byte objects will always be different and the paint will have no reference as to what the image source is. I think we will just need to forego any style matching here because we can't check the equality of values

You're right, I feel we can do what you said and not do any style matching. We should still be able to apply a style if name matches, and in the future we could store asset tokens in non-local styles as well.

So then lets remove the parts of the code that do the matching and the style id backup parts?

2022-10-13 07:06 UTC, six7 requested changes
Few things:
- When we apply a token and we fail to fetch, can we show an ErrorNotification in the Figma UI? we do this in other places already (notifyTo..)

2022-10-14 21:25 UTC, six7 approved these changes

2022-10-14 21:26 UTC, merged