1200 introduce onboarding modal flow
six7/figma-tokens pull request #1339
Opened 2022-10-12 12:16 UTC by MightyDevKnight

![ScreenShot_20221012211313](https://user-images.githubusercontent.com/102773603/195340198-b43e1e44-cc06-4f77-9d65-0959b37adeae.jpeg)
![ScreenShot_20221012211318](https://user-images.githubusercontent.com/102773603/195340215-31fac0ad-a849-4641-8052-32fbf662ed0d.jpeg)
![ScreenShot_20221012211325](https://user-images.githubusercontent.com/102773603/195340217-04621c80-29bf-4813-a0cb-15a96c6a885f.jpeg)
![ScreenShot_20221012211334](https://user-images.githubusercontent.com/102773603/195340220-c78cf61c-cb49-4146-8eb8-c67cb6a3611f.jpeg)

2022-10-13 06:53 UTC, six7 requested changes
I'd like to move away from the FALLBACK_LAST_OPENED both in the code you changed here as well as in src/utils/getLastOpened.ts -> if the user has never opened the plugin, the property should not be set - and we can show the onboarding modal

2022-10-13 06:53 UTC, six7 commented on src/app/components/OnboardingFlow.tsx
> +  const FALLBACK_LAST_OPENED = 1616241985291;
Instead of using a date here I would like this to work like this:
- If there is no "lastOpened" flag set on the client, show the onboarding flow.
- After opening the plugin once, we set lastOpened
- Any subsequent launch would no longer show the onboardingModal because there is a `lastOpened` set.

That way we do not need this fallback_last_opened and it will be easy for us to reset this later - by just removing `lastOpened`.

2022-10-13 06:53 UTC, six7 commented on src/app/components/OnboardingFlow.tsx
> +        filename: 'https://user-images.githubusercontent.com/4548309/190957841-bc189fb7-0351-4206-9e38-a4b85506d300.png',
Can you add these images to our local assets?

2022-10-13 06:53 UTC, six7 commented on src/app/components/OnboardingFlow.tsx
> +              // eslint-disable-next-line no-underscore-dangle
is this needed? i dont see no underscore

2022-10-13 06:53 UTC, six7 commented on src/utils/storyblok.ts
> +const FALLBACK_LAST_OPENED = 1616241985291;
same as above

2022-10-14 07:01 UTC, six7 commented
@MightyDevKnight can we get tests to pass & coverage?

2022-10-14 12:44 UTC, LiamMartens requested changes
@six7 @MightyDevKnight just 1 minor consistency change - but separately, it's probably worth converting those into WebPs since they are anywhere between 75 and 50% smaller overall

2022-10-14 12:44 UTC, LiamMartens commented on src/app/components/AppContainer/__tests__/AppContainerIntegration.test.tsx
> +        lastOpened: Date.now(),
I guess this should not be a date anymore? Just for consistency

2022-10-14 21:37 UTC, six7 approved these changes

2022-10-14 21:37 UTC, six7 commented on src/app/components/AppContainer/__tests__/AppContainerIntegration.test.tsx
> +        lastOpened: Date.now(),
i think it should still be a date? like we store Date.now() when you open the plugin. but if you never opened it, it will be at 0.

2022-10-14 21:37 UTC, merged