1308 optimize themesjson file
six7/figma-tokens pull request #1405
Opened 2022-11-03 11:42 UTC by swordEdge

![image](https://user-images.githubusercontent.com/25951419/199712026-f6e6a2d2-df71-427e-a11f-d26873f1e072.png)
![image](https://user-images.githubusercontent.com/25951419/199712087-ff1d835c-c133-4089-b986-5217a379af77.png)

2022-11-06 21:33 UTC, LiamMartens requested changes
@swordEdge I would consolidate this logic inside theme related logic so it's more centralized;
specifically in 2 places:
- `setTokenData.ts` - we can add a `status !== TokenSetStatus.DISABLED` into the selectedTokenSets filter to remove the DISABLED status token sets from the theme when reading (this will prompt the user to write back to the repo since it won't match anymore - but from my POV this is okay since we are changing the data @six7 )
- `saveTheme` - here we can filter out the disabled token sets when updating/adding the theme. This way they won't make into the data in the first place.

This way there is a much better separation of concerns between the remote content/file logic and the themes logic.

2022-11-06 21:33 UTC, LiamMartens commented on src/app/store/providers/bitbucket/bitbucket.tsx
> +              const recoveredThemes = recoverOptimizedThemes(content.themes, content.tokens);
@swordEdge why is this necessary? I would say it is probably okay to notify the user of the changed values because of the optimization and to let them simply write it back to the remote repository.

FYI @six7

2022-11-07 06:59 UTC, swordEdge commented on src/app/store/providers/bitbucket/bitbucket.tsx
> +              const recoveredThemes = recoverOptimizedThemes(content.themes, content.tokens);
> @swordEdge why is this necessary? I would say it is probably okay to notify the user of the changed values because of the optimization and to let them simply write it back to the remote repository.
> 
> FYI @six7

@LiamMartens You're right. Right now users already have the non-optimized themes, so if we remove this part, plugin asks to write again to remote repository.

2022-11-08 10:16 UTC, swordEdge commented on src/app/store/providers/bitbucket/bitbucket.tsx
> +              const recoveredThemes = recoverOptimizedThemes(content.themes, content.tokens);
@six7 Waiting for your response.

2022-11-08 19:24 UTC, six7 commented on src/app/store/providers/bitbucket/bitbucket.tsx
> +              const recoveredThemes = recoverOptimizedThemes(content.themes, content.tokens);
Yes, lets ask and push back 👍

2022-11-11 13:46 UTC, LiamMartens approved these changes

2022-11-11 17:20 UTC, merged