1425 gradients cant be used directly in compositions
six7/figma-tokens pull request #1447
Opened 2022-11-22 13:16 UTC by swordEdge

https://www.loom.com/share/c5aaf49cd71f491a92d22efe2e5ff40f

2022-11-22 20:03 UTC, six7 requested changes

2022-11-22 20:03 UTC, six7 commented on src/plugin/setValuesOnNode.ts
> -        if ('fills' in node && data.asset) {
Is this by accident?

2022-11-23 02:04 UTC, swordEdge commented on src/plugin/setValuesOnNode.ts
> -        if ('fills' in node && data.asset) {
@six7 data.assets condition is not neccessary. You'll notice that if you see the source code. That's why I removed this part.

2022-11-23 07:02 UTC, six7 approved these changes

2022-11-23 07:02 UTC, merged