feat: options for token-transformer & expandTypography option for style-dictionary compatibility
six7/figma-tokens pull request #396
Opened 2022-01-12 14:55 UTC by jeffreydelooff

Currently the **token-transformer** CLI automatically expands typography types to:

```
"typographyName": {
  "fontFamily": {
    "value": "Roboto"
  },
  "fontSize": {
    "value": 18
  }
}
```
For style-dictionary compatibility it would be easier to have the following format (especially for custom formats):
```
"typographyName": {
  "type": "typography",
  "value": {
    "fontFamily": "Roboto",
    "fontSize": 18
  }
}
```
so we can use the **type** to group/filter typographies together.

This PR adds:
* yargs set-up for token-transformer inputs & validation
* possibility to add options for transformations (here I introduced expandTypography so users can opt-out of this auto expansion)

2022-01-13 12:54 UTC, six7 requested changes
Other than those changes this looks good! 🎉 Thank you for this!

Could we get those changes in? I was able to run it by removing the `fallback` param to try it out, but I guess that's needed for tests?

2022-01-13 12:54 UTC, six7 commented on webpack-transform.config.js
> +        fallback: {
This one fails for me. The plugin is still running webpack 4. A quick search seemed to indicate that resolve.fallback is part of webpack 5? Can we go without this? I could imagine an upgrade to webpack to be more than just a version bump

2022-01-13 12:54 UTC, six7 commented on src/utils/convertTokensObjectToResolved.ts
> +        expandTypography: true,
I'm wondering if we should make the new way the default and introduce a breaking change?  I've heard quite a bit of feedback that the current behavior is not expected so I'd be 👍 for changing this to expandTypography: false

2022-01-13 12:54 UTC, six7 commented on token-transformer/README.md
> +--expandTypography: true|false in order to opt-out of automatic expansion of typography types (default: true)
same, let's use default: false

2022-01-13 13:06 UTC, jeffreydelooff commented on webpack-transform.config.js
> +        fallback: {
Indeed, I think it already worked without this because of v4. I have removed it.

2022-01-13 13:06 UTC, jeffreydelooff commented on src/utils/convertTokensObjectToResolved.ts
> +        expandTypography: true,
Yes, you are right. It feels also the recommended way to not expand it at all. 👍

2022-01-13 13:44 UTC, six7 approved these changes
Nice! LGTM! 🎉  Will release later today

2022-01-13 13:47 UTC, merged

2022-01-18 16:49 UTC, avendiart commented
@six7 has this been released? `0.0.16` still seems to always expand by default.

2022-01-18 17:52 UTC, six7 commented
> @six7 has this been released? `0.0.16` still seems to always expand by default.

There's been a bug in this recent version that @jeffreydelooff [fixed](https://github.com/six7/figma-tokens/pull/404) today - I just released it and should work now 🙏