Add expandShadow parameter for boxShadow types
six7/figma-tokens pull request #501
Opened 2022-03-03 18:42 UTC by iShavgula-TacTill

2022-03-04 14:51 UTC, six7 requested changes

2022-03-04 14:51 UTC, six7 commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos
Let's not change gitignore

Other than that this PR looks great!

2022-03-04 14:55 UTC, iShavgula-TacTill commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos
Good to hear !

I used this [platform](https://www.toptal.com/developers/gitignore) to add OS X specific paths. Otherwise, I'd get many `.DS_Store` files, one in every folder.

2022-03-04 15:11 UTC, iShavgula-TacTill commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos
I reverted the changes for the .gitignore file.

2022-03-04 15:24 UTC, six7 requested changes
I noticed it doesn't yet work for shadow tokens that have multiple shadows setup (with an array as a value):

```
{
  "boxShadow": {
    "default": {
      "value": [
        {
          "x": 5,
          "y": 5,
          "spread": 3,
          "color": "rgba(0, 0, 0, 0.15)",
          "blur": 5,
          "type": "dropShadow"
        },
        {
          "x": 4,
          "y": 4,
          "spread": 6,
          "color": "#00000033",
          "blur": 5,
          "type": "innerShadow"
        }
      ],
      "type": "boxShadow"
    },
    "single": {
      "value": {
        "x": 5,
        "y": 5,
        "spread": 3,
        "color": "rgba(0, 0, 0, 0.15)",
        "blur": 5,
        "type": "dropShadow"
      },
      "type": "boxShadow"
    }
  }
}
```

2022-03-04 16:07 UTC, iShavgula-TacTill commented
Hah, I just noticed that `+` button, didn't know that was possible.

2022-03-06 12:06 UTC, six7 commented
> Hah, I just noticed that `+` button, didn't know that was possible.

😀 I think it's one of the more common scenarios as most shadows have multiple levels of depth, so I'd love it if we found a way to make that work

2022-03-09 10:25 UTC, iShavgula-TacTill commented
Hey,
I just pushed changes that I made earlier, I was waiting for a confirmation from you on Slack.
Please, let me know if there are other changes that to be done.

2022-03-10 09:13 UTC, six7 requested changes
Nice! Sorry, must've missed the Slack message. Works as expected 👍. Can you add a test case for single value tokens and multi value tokens to `src/utils/convertTokensObjectToResolved.test.ts` ? Then we'd be good to merge! 🎉

2022-03-14 18:21 UTC, merged