Feat 27/autocomplete
six7/figma-tokens pull request #575
Opened 2022-04-02 11:39 UTC by srinivas0210

2022-04-08 15:44 UTC, LiamMartens requested changes

2022-04-08 15:44 UTC, LiamMartens commented on src/app/components/Autosuggest.tsx
> +  const handleKeyUp = (e: { preventDefault?: any; which?: any }) => {
Any functions inside a functional component should be properly wrapped with `useCallback` for performance reason.
It would also be great to type these events correctly

In this case I believe it would be `(e: React.KeyboardEvent<HTMLDivElement>)`

2022-04-08 15:44 UTC, LiamMartens commented on src/app/components/Autosuggest.tsx
> +  const filteredValue = inputValue.replace(/[^a-zA-Z0-9.]/g, ''); // removing non-alphanumberic except . from the input value
Can we `useMemo` this `useMemo(() => inputValue.replace(/[^a-zA-Z0-9.]/g, ''), [inputValue])`

2022-04-08 15:44 UTC, LiamMartens commented on src/app/components/Autosuggest.tsx
> +  const focused = document.querySelector('.autosuggest-item-focused'); // get the element with this className, this is helpful for autoscroll upto focused element
Is there any possibility to implement this without using a `querySelector`? This is generally bad practice within React

2022-04-08 15:44 UTC, LiamMartens commented on src/app/components/Autosuggest.tsx
> +  const handleKeyDown = (e: { preventDefault?: any; which?: any }) => {
Same comment as before - make this a `useCallback`

2022-04-08 15:44 UTC, LiamMartens commented on src/app/components/Autosuggest.tsx
> +  const getHighlightedText = (text: string, highlight: string) => {
This should also be a `useMemo`

2022-04-08 15:44 UTC, LiamMartens commented on src/app/components/Autosuggest.tsx
> +    const filteredOnType = resolvedTokens.filter((token: any) => token?.type === type);
Not sure if avoidable in this case but let's refrain from using `any` for any new code when possible

2022-04-08 15:44 UTC, LiamMartens commented on src/app/components/Autosuggest.tsx
> +          {mappedValues.map((token: any, index: number) => (
Also here - let's try to type this correctly

2022-04-08 15:44 UTC, LiamMartens commented on src/app/components/Autosuggest.tsx
> +              onClick={() => setInputValue(`{${token.name}}`)}
This should also be a `useCallback`

2022-04-08 15:44 UTC, LiamMartens commented on src/app/components/EditTokenForm.tsx
> +                  <StyledInputSuffix onClick={() => setShowAutoSuggest(!showAutoSuggest)}>
Make the `onClick` a `useCallback`

2022-04-08 15:44 UTC, LiamMartens commented on src/app/styles/autosuggest.css
> +.dropdown {
Is there any way we can style this with stitches instead?

2022-04-13 14:25 UTC, LiamMartens commented on src/app/components/DownshiftInput.tsx
> +  resolvedTokens: any;
We need to get out of the `any` hell. This should be `ResolveTokenValuesResult`. It may not be 100% correct but it's better than any

2022-04-13 14:25 UTC, LiamMartens commented on src/app/components/DownshiftInput.tsx
> +  setInputValue: Function;
We should not use `Function`. It is too generic and could accept any kind of paramter and return any kind of value. It should be a properly typed function definition ie `(param: string) => void`

2022-04-13 14:25 UTC, LiamMartens commented on src/app/components/EditTokenForm.tsx
> +                  onClick={React.useCallback(() => setShowAutoSuggest(!showAutoSuggest), [showAutoSuggest])}
I appreciate the useCallback but it shoulnd't be used within the render return. Please move it to a separate variable before the render code

2022-04-13 16:29 UTC, srinivas0210 commented on src/app/components/DownshiftInput.tsx
> +                      backgroundColor: highlightedIndex === index ? '#18a0fb' : 'white',
Hey..I missed this 👍

2022-04-13 16:44 UTC, srinivas0210 commented on src/app/components/DownshiftInput.tsx
> +                .filter(
sure, makes sense 👍

2022-04-13 16:49 UTC, srinivas0210 commented
Hey @LiamMartens , Thanks for reviewing my PR, I have just resolved your comments, Please review 😃

2022-04-19 18:23 UTC, six7 commented
Do you need any help with this one?

2022-04-23 11:10 UTC, closed without merging