sync with gitlab, pull from gitlab, upload tokens, used @gitbreak/bro…
six7/figma-tokens pull request #579
Opened 2022-04-06 13:05 UTC by swordEdge

…wser as a gitlab client

2022-04-06 19:00 UTC, six7 reviewed
thought i'd give you some comments while you're still working on this. this looks great so far! 🎉

2022-04-07 17:46 UTC, LiamMartens requested changes
Left 2 comments

2022-04-07 17:46 UTC, LiamMartens commented on src/app/components/SyncSettings.tsx
> +  const selectedRemoteProvider = () => [StorageProviderType.JSONBIN, StorageProviderType.GITHUB, StorageProviderType.GITLAB, StorageProviderType.URL].includes(
Could we just update this with a `useMemo` hook whilst we're working on this.
[useMemo](https://reactjs.org/docs/hooks-reference.html#usememo)

2022-04-07 17:46 UTC, LiamMartens commented on src/app/components/SyncSettings.tsx
> +                onClick={() => {
Let's make use of React's useCallback hook so we don't create a new function reference every cycle

2022-04-16 02:54 UTC, swordEdge commented
@six7 @LiamMartens 

> Errors on Node.js CI / Create Package, Node.js CI / Tests

The dependency(gitbeaker/browser) is relying on Node.js 16+, but Vercel currently does not have support yet, as we are dependent on AWS.
https://github.com/vercel/community/discussions/37

2022-04-20 07:07 UTC, six7 commented
> 

I think it's fine. Vercel is only required for previews, we should not make the plugin dependable on that.

Any updates on the failings tests? Would love to get this merged.

2022-04-21 12:26 UTC, LiamMartens approved these changes

2022-04-21 12:27 UTC, LiamMartens commented
@swordEdge just need to update the`node.js.yml` workflow to use Node 14 and we should be all good

2022-04-21 12:36 UTC, merged