View token layers
six7/figma-tokens pull request #580
Opened 2022-04-06 15:05 UTC by roppazvan

https://github.com/six7/figma-tokens/issues/513

* created a new TokenLayers component
* Added radix icons for the layer listing

2022-04-06 19:08 UTC, six7 requested changes
🎉 just some minor color usage comments. i can't run the plugin currently (seems to be connected to the upgraded dropdown package)

2022-04-06 19:08 UTC, six7 commented on src/app/components/inspector/TokenNodes.tsx
> +            <Box css={{ color: '#575757' }}>{nodes.length}</Box>
```suggestion
            <Box css={{ color: '$textMuted' }}>{nodes.length}</Box>
```

2022-04-06 19:08 UTC, six7 commented on src/app/components/inspector/TokenNodes.tsx
> +                background: 'rgba(196, 196, 196, 0.15)',
```suggestion
                background: '$bgSubtle',
```

sorry, that was my bad in the design

2022-04-06 19:08 UTC, six7 commented on src/app/components/inspector/TokenNodes.tsx
> +              borderRadius: '6px',
```suggestion
              borderRadius: '$default',
```

2022-04-06 19:08 UTC, six7 commented on src/app/components/inspector/getNodeIcon.tsx
> +            fill: '#fff',
```suggestion
            fill: '$contextMenuForeground',
```

i dont know if stitches picks up svg fill - could be we'll have to change that. however we'd want to use tokens here as we might introduce new themes in the future so let's keep raw hex values out of this

2022-04-08 03:20 UTC, esthercheran commented
FT-40 & FT-41

2022-04-08 15:37 UTC, LiamMartens requested changes

2022-04-08 15:37 UTC, LiamMartens commented on src/app/components/inspector/TokenNodes.tsx
> +          {getNodeIcon(type)}
Would be great if we can useMemo this so it doesn't get re-evaluated each time

2022-04-08 15:37 UTC, LiamMartens commented on src/app/components/inspector/TokenNodes.tsx
> +  function getNode({ id, name, type }: NodeInfo) {
Can we just split this into it's own component. It is bad practice to create new component/functions like this because it can cause performance issues.

2022-04-08 15:37 UTC, LiamMartens commented on src/app/components/inspector/TokenNodes.tsx
> +      <DropdownMenu.Item key={id} onSelect={() => goToNodeId(id)}>
When split into its own component the onSelect can also be attached to a useCallback hook, again to prevent any unwanted re-renders due to reference changes

2022-04-08 15:37 UTC, LiamMartens commented on src/app/components/inspector/getNodeIcon.tsx
> +function getNodeIcon(type: NodeType) {
this should either move to utils or be transformed into a proper component. Now it's in the components folder appearing to be a component but it isnt.

2022-04-08 15:37 UTC, LiamMartens commented on src/types/messages.tsx
> +export type SelectNodes = {
Can we change this to `SelectNodesPluginMessage`, only because that's also the name of all the other types

2022-04-11 11:52 UTC, LiamMartens approved these changes

2022-04-11 16:57 UTC, merged