Ft 44 combine sync and settings tab
six7/figma-tokens pull request #603
Opened 2022-04-13 13:48 UTC by srinivas0210

2022-04-13 19:18 UTC, six7 reviewed
Can you do a Search for `syncsettings` and replace that with `settings`? We currently set tab to syncsettings when a file has github sync but the user doesn't have the correct credentials

2022-04-13 19:18 UTC, six7 commented on src/app/components/Navbar.tsx
> +<Stack gap={0} direction="row" align="center" justify="between" css={{ width: '100%' }}>
This seems to be a mistake?

2022-04-13 19:19 UTC, six7 commented on src/app/components/Settings.tsx
> +  const [confirmModalVisible, showConfirmModal] = React.useState(false);
Can you keep Syncsettings as their own component and import it here?? That way this files does not get as big.

2022-04-13 19:20 UTC, six7 requested changes
Some comments and remember to change tab for StartScreen.

Also, make sure to remove any remnants of SyncSettings, especially in constants / Tabs

2022-04-14 03:50 UTC, LiamMartens requested changes

2022-04-14 03:50 UTC, LiamMartens commented on src/app/components/Settings.tsx
> +  const handleEditClick = (provider) => {
These function handlers should be `useCallback`'s to prevent unnecessary re-renders

2022-04-14 03:50 UTC, LiamMartens commented on src/app/components/Settings.tsx
> +  const selectedRemoteProvider = () => [StorageProviderType.JSONBIN, StorageProviderType.GITHUB, StorageProviderType.URL].includes(
This can probably be a static `useMemo` instead. We don't need to re-evaluate this each time

2022-04-14 03:50 UTC, LiamMartens commented on src/app/components/Settings.tsx
> +  const storedApiProviders = () => apiProviders.filter((item) => item.provider === localApiState?.provider);
Same with this

2022-04-14 03:50 UTC, LiamMartens commented on src/app/components/Settings.tsx
> +  const storageProviderText = () => {
And this one as well

2022-04-14 03:50 UTC, LiamMartens commented on src/app/components/Settings.tsx
> +          onSuccess={() => {
This should be a `useCallback`

2022-04-14 03:50 UTC, LiamMartens commented on src/app/components/Settings.tsx
> +          onClose={() => setShowEditStorageModalVisible(false)}
Any handlers should be `useCallback`

2022-04-20 07:05 UTC, closed without merging