feat: Use token set as source
six7/figma-tokens pull request #604
Opened 2022-04-13 21:49 UTC by LiamMartens

2022-04-14 18:42 UTC, six7 commented on src/plugin/node.ts
> +  tokens: Map<string, TokenArrayGrou[number]>,
this feels like a mistake?

2022-04-14 18:43 UTC, six7 commented on src/utils/convertTokensObjectToResolved.ts
> +    // which in turn is only used for a local script -- in which case for now we do not
correct, the token-transformer has a way to exclude token sets which is fine for now. users basically first define all inputs and later define which sets should be excluded from output

2022-04-14 18:56 UTC, six7 requested changes
Just this one mini comment that feels like a mistake, other than this good to merge!

2022-04-14 18:57 UTC, LiamMartens commented
@six7 great! I fixed the typing so we can go ahead and merge this so we can continue with the themes :+1:

2022-04-14 18:59 UTC, six7 approved these changes

2022-04-14 19:00 UTC, six7 commented
Nice! 🎉

2022-04-14 20:30 UTC, merged

2022-04-21 19:58 UTC, mstllc commented
@LiamMartens what does this `Treat as source` option actually do? 😄

2022-04-22 05:36 UTC, six7 commented
> @LiamMartens what does this `Treat as source` option actually do? 😄 

It doesnt include the tokens in the actual output, like if you wouldn't want your global tokens to create styles for you, as all you care about might be just the theme specific semantic tokens