Ft 43 git sync introduce branch switch 341
six7/figma-tokens pull request #605
Opened 2022-04-14 08:22 UTC by swordEdge

2022-04-15 06:49 UTC, six7 reviewed
Bit of functional feedback:
- Can we remove the down arrow next to the branch name? The branch name with a hover background would be enough.
- When a user has to enter a new branch name (e.g. by using create a new branch from..) can we focus the input? So the user doesnt have to click into that?
- I tried creating a new branch, but it seems like it created 2

![image](https://user-images.githubusercontent.com/4548309/163531057-81c416b4-3ae2-49d8-bb8b-b3a20f8893b5.png)

- The interaction when a user has local changes feels a bit weird right now as two modals pop up after another. I'll think about this some more, but I feel like we should consolidate that to 1 modal

2022-04-16 02:56 UTC, swordEdge commented
> * Can we remove the down arrow next to the branch name? The branch name with a hover background would be enough.
This is fixed.

> * I tried creating a new branch, but it seems like it created 2
This is fixed.

> * The interaction when a user has local changes feels a bit weird right now as two modals pop up after another. I'll think about this some more, but I feel like we should consolidate that to 1 modal
Waiting for instruction.
@six7

2022-04-16 13:28 UTC, six7 commented
> _Waiting for instruction._
> 
> 
> 
> @six7 

Can we make it like this: 
You have unsaved changes. [Cancel] [Discard changes].
`Cancel`: Cancels the action, user stays on current branch, still has their local changes
`Discard changes`: New branch is immediately checked out and pulled, no second modal.

2022-04-16 17:48 UTC, swordEdge commented
> Can we make it like this: You have unsaved changes. [Cancel] [Discard changes]. `Cancel`: Cancels the action, user stays on current branch, still has their local changes `Discard changes`: New branch is immediately checked out and pulled, no second modal.

2022-04-17 23:59 UTC, six7 commented on src/app/components/Footer.tsx
> +            <button onClick={() => pullTokens({})} type="button" className="button button-ghost">
can we make sure to also specify usedTokenSet here? we did this before, having that here makes sure that the token sets the user had active before stay active. right now they get reset.

2022-04-17 23:59 UTC, six7 commented on src/app/components/BranchSelector.tsx
> +    if (await askUserIfPull()) await pullTokens({ context: { ...apiData, branch } });
same: can we make sure to also specify usedTokenSet here? we did this before, having that here makes sure that the token sets the user had active before stay active. right now they get reset.

2022-04-18 18:58 UTC, six7 commented
Thanks for the changes! Feeling much better that way 🔥

2022-04-18 19:01 UTC, six7 commented on src/app/components/Input.tsx
> +          autoFocus={autofocus}
I'm not sure autofocus works right now, it's not focusing for me.

2022-04-18 19:03 UTC, six7 commented on src/app/components/BranchSwitchMenu.tsx
> +const itemStyles = {
could this just use a DropdownMenu? Or do we have to recreate all those styles?

2022-04-19 10:14 UTC, swordEdge commented on src/app/components/BranchSwitchMenu.tsx
> +const itemStyles = {
> could this just use a DropdownMenu? Or do we have to recreate all those styles?

I've tried to use the existing DropdownMenu but the submenu appeared under the trigger item and also many styles were not good fit to the DESIGN of the branch switching menu.

2022-04-19 13:42 UTC, swordEdge commented on src/app/components/Footer.tsx
> +            <button onClick={() => pullTokens({})} type="button" className="button button-ghost">
> can we make sure to also specify usedTokenSet here? we did this before, having that here makes sure that the token sets the user had active before stay active. right now they get reset.

Fixed!

2022-04-19 13:42 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
> +    if (await askUserIfPull()) await pullTokens({ context: { ...apiData, branch } });
> same: can we make sure to also specify usedTokenSet here? we did this before, having that here makes sure that the token sets the user had active before stay active. right now they get reset.

Fixed!

2022-04-19 13:43 UTC, swordEdge commented
> Can we make it like this: You have unsaved changes. [Cancel] [Discard changes]. `Cancel`: Cancels the action, user stays on current branch, still has their local changes `Discard changes`: New branch is immediately checked out and pulled, no second modal.

Fixed!

2022-04-19 13:45 UTC, swordEdge commented on src/app/components/BranchSwitchMenu.tsx
> +const itemStyles = {
@six7 do you have any other ideas?

2022-04-19 18:13 UTC, six7 commented on src/app/components/BranchSwitchMenu.tsx
> +const itemStyles = {
Got it, other than that it's 👍 from my end! Would you be able to add tests? IMO we should write tests for any new features we're building so we can increase test coverage. Once Liam has reviewed we can merge.

2022-04-21 12:42 UTC, LiamMartens requested changes

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/BranchSelector.tsx
> +  async function askUserIfPull(): Promise<boolean> {
This should be a `useCallback`

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/BranchSelector.tsx
> +  async function askUserIfPushChanges(): Promise<boolean> {
Same with any other function created inside this component.

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/BranchSelector.tsx
> +                  {checkForChanges()
Would be better if we can memo this effect otherwise it will run on ever render

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/BranchSelector.tsx
> +                    <BranchSwitchMenuRadioItem key={index} value={branch} onSelect={() => onBranchSelected(branch)}>
Move this to a `useCallback` as well so we're not creating new functions each time. Probably better to move these entries into their own smaller component anyways to separate concerns.
(the code that's inside the `map`)

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/BranchSelector.tsx
> +                    <BranchSwitchMenuItem key={index} onSelect={() => createNewBranchFrom(branch)}>
Same comment on this; `useCallback` it and move to it's own small component

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/BranchSwitchMenu.tsx
> +const itemStyles = {
@six7 we may want to reconcile some of this from design up - so things can be reused more (not necessary now)

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/Footer.tsx
> +  const transformProviderName = (provider: StorageProviderType) => {
make this a `useCallback` like the `checkForChanges` function

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/Footer.tsx
> +            <button onClick={() => pullTokens({ usedTokenSet })} type="button" className="button button-ghost">
Any handlers should be `useCallback`'ed

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/Footer.tsx
> +              onClick={() => pushTokens()}
Same comment about the handlers

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/Footer.tsx
> +              {checkForChanges() && <div className="absolute top-0 right-0 w-2 h-2 rounded-full bg-primary-500" />}
Same comment as in some other file - if we can memo result of this function that would be great so we can not re-run the logic on each cycle.

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/Initiator.tsx
> +                const branches = await fetchGithubBranches({
@six7 not for now but we should think about a more central way of managing all our remote/async data in the future. It's very scattered at the moment which can cause more bugs in the long run due to it's disconnected nature

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/Input.tsx
> +          autoFocus={autofocus}
not sure if this has been resolved yet?

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/modals/CreateBranchModal.tsx
> +  const handleCreateNewClick = async () => {
Let's make sure we do the hooks on new code

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/modals/CreateBranchModal.tsx
> +  const inputRef = React.useRef(null);
This should be typed correctly. In this case it should be `useRef<HTMLInputElement | null>`

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/modals/CreateBranchModal.tsx
> +  const [formFields, setFormFields] = React.useState({});
This should also be typed correctly. Let's make sure the next developer knows exactly what fields could end up in here

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/modals/CreateBranchModal.tsx
> +  const handleChange = (e: any) => {
The event should not use `any` - this should be `(e: React.ChangeEvent<HTMLInputElement>)`

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/modals/CreateBranchModal.tsx
> +  const handleSubmit = (e: any) => {
This can also be typed `(e: React.FormEvent<HTMLFormElement>)`

2022-04-21 12:42 UTC, LiamMartens commented on src/app/components/modals/CreateBranchModal.tsx
> +    <Modal large isOpen={isOpen} close={() => onClose(false)}>
Let's move the handler to a `useCallback` as well

2022-04-24 17:10 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
> +  async function askUserIfPull(): Promise<boolean> {
Fixed!

2022-04-24 17:10 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
> +  async function askUserIfPushChanges(): Promise<boolean> {
Fixed!

2022-04-24 17:27 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
> +                    <BranchSwitchMenuRadioItem key={index} value={branch} onSelect={() => onBranchSelected(branch)}>
Fixed!

2022-04-24 17:32 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
> +                    <BranchSwitchMenuItem key={index} onSelect={() => createNewBranchFrom(branch)}>
Fixed!

2022-04-24 17:35 UTC, swordEdge commented on src/app/components/Footer.tsx
> +  const transformProviderName = (provider: StorageProviderType) => {
Fixed!

2022-04-24 17:39 UTC, swordEdge commented on src/app/components/Footer.tsx
> +              onClick={() => pushTokens()}
Fixed!

2022-04-24 17:39 UTC, swordEdge commented on src/app/components/Footer.tsx
> +            <button onClick={() => pullTokens({ usedTokenSet })} type="button" className="button button-ghost">
Fixed!

2022-04-24 17:44 UTC, swordEdge commented on src/app/components/modals/CreateBranchModal.tsx
> +  const handleCreateNewClick = async () => {
fixed!

2022-04-24 17:45 UTC, swordEdge commented on src/app/components/modals/CreateBranchModal.tsx
> +  const inputRef = React.useRef(null);
Fixed!

2022-04-24 17:46 UTC, swordEdge commented on src/app/components/modals/CreateBranchModal.tsx
> +  const handleChange = (e: any) => {
Fixed!

2022-04-24 17:47 UTC, swordEdge commented on src/app/components/modals/CreateBranchModal.tsx
> +  const handleSubmit = (e: any) => {
Fixed!

2022-04-24 17:49 UTC, swordEdge commented on src/app/components/modals/CreateBranchModal.tsx
> +    <Modal large isOpen={isOpen} close={() => onClose(false)}>
Fixed!

2022-04-25 13:24 UTC, swordEdge commented on src/app/components/Footer.tsx
> +              {checkForChanges() && <div className="absolute top-0 right-0 w-2 h-2 rounded-full bg-primary-500" />}
Fixed!

2022-04-25 14:38 UTC, swordEdge commented on src/app/components/Input.tsx
> +          autoFocus={autofocus}
Resolved!

2022-04-25 14:58 UTC, LiamMartens requested changes

2022-04-25 14:58 UTC, LiamMartens commented on src/app/components/BranchSelector.tsx
>    const createNewBranchFrom = async (branch: string) => {
As mentioned before - all functions created inside components should be either `useCallback` or `useMemo`

2022-04-25 14:58 UTC, LiamMartens commented on src/app/components/BranchSelector.tsx
> +  const BranchSwitchMenuRadioElement = ({ branch, index } : { branch: string, index:number }) => {
If possible - let's move these to their own component files

2022-04-26 01:24 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
> +  const BranchSwitchMenuRadioElement = ({ branch, index } : { branch: string, index:number }) => {
I think it's impossible to move these to their own component files because the function outside was used in it. @LiamMartens

2022-04-26 01:26 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
>    const createNewBranchFrom = async (branch: string) => {
![image](https://user-images.githubusercontent.com/25951419/165200493-e6d4ae11-4971-4785-b1f9-a494a0b71a3e.png)

**createNewBranchFrom** function was used once in a function which is wrapped by useCallback. Do we still need to redefine with useCallback or useMemo? @LiamMartens

2022-04-26 16:00 UTC, LiamMartens commented on src/app/components/BranchSelector.tsx
>    const createNewBranchFrom = async (branch: string) => {
Yes - really this should be separated because of the same reason as the `BranchSwitchMenuRadioElement` variable

2022-04-27 06:26 UTC, six7 approved these changes

2022-04-27 06:27 UTC, six7 commented
@swordEdge changed base to `next` - there's one more conflict for Navbar, and the two comments from Liam - other than that let's get this merged once that is done.

2022-04-28 06:31 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
> +  const BranchSwitchMenuRadioElement = ({ branch, index } : { branch: string, index:number }) => {
> It would be better to separate it, even if it is in this same file and pass the function as props. This way the function reference doesn't change and will never cause a re-render

> fixed

2022-04-28 06:31 UTC, swordEdge commented on src/app/components/BranchSelector.tsx
>    const createNewBranchFrom = async (branch: string) => {
fixed

2022-04-28 09:55 UTC, merged