deep linking aliases
six7/figma-tokens pull request #621
Opened 2022-04-19 13:30 UTC by swordEdge

2022-04-19 18:14 UTC, six7 commented
Can you add tests for this scenario? The alias files should already have some tests setup, let's extend them.

2022-04-22 14:10 UTC, six7 commented
fyi: theres some failing tests @swordEdge

2022-04-24 00:16 UTC, swordEdge commented
> Can you add tests for this scenario? The alias files should already have some tests setup, let's extend them.

done!

2022-04-24 00:18 UTC, swordEdge commented
> * Don't show the red dot

fixed!
> * ideally, it would show the fully resolved value, not $16. In that case, 16px.

fixed!

2022-04-24 16:15 UTC, six7 requested changes
i think there's some unintended changes here, let's not include our stitches theme config in user's aliases

i also noticed it currently still shows the red dot if the user used the $ notation, the preview doesnt work as well if the user used the $ notation.

<img width="227" alt="image" src="https://user-images.githubusercontent.com/4548309/164985892-483258d4-bd12-4856-94d5-fd6c596df826.png">
<img width="316" alt="image" src="https://user-images.githubusercontent.com/4548309/164985924-131eedaf-790b-4260-b0ba-bf6150d33a79.png">
<img width="241" alt="image" src="https://user-images.githubusercontent.com/4548309/164985901-0f7db46d-b590-4a5d-ba2f-b23f030a74f8.png">
<img width="253" alt="image" src="https://user-images.githubusercontent.com/4548309/164985908-1548a7db-3bae-4d1e-9607-09c7ce78f429.png">

2022-04-24 16:15 UTC, six7 commented on src/utils/alias/getAliasValue.ts
> +import { theme } from '@/stitches.config';
i think this is a mistake? the stitches config is not required here

2022-04-24 16:15 UTC, six7 commented on src/utils/alias/getAliasValue.ts
> +            resolved = theme.space[`${sizeProperty}`].value;
why is this here? our stitches theme config is definitely not something our users would want to alias?

2022-04-25 03:24 UTC, swordEdge commented on src/utils/alias/getAliasValue.ts
> +import { theme } from '@/stitches.config';
Fixed!

2022-04-25 03:24 UTC, swordEdge commented on src/utils/alias/getAliasValue.ts
> +            resolved = theme.space[`${sizeProperty}`].value;
Fixed!

2022-04-25 03:25 UTC, swordEdge commented
> i think there's some unintended changes here, let's not include our stitches theme config in user's aliases

Fixed!

2022-04-25 03:25 UTC, swordEdge commented
> Can you add tests for this scenario? The alias files should already have some tests setup, let's extend them.

Done!

2022-04-26 17:30 UTC, six7 commented on src/utils/alias/getAliasValue.ts
> +          type TokenNameNodeType = string | undefined;
This can probably move to the top of the file or to its own file?

2022-04-26 17:35 UTC, six7 approved these changes
Looking good! I had one comment regarding where that type is being declared. Other than that this works great!

2022-04-27 01:04 UTC, LiamMartens approved these changes

2022-04-27 01:07 UTC, swordEdge commented on src/utils/alias/getAliasValue.ts
> +          type TokenNameNodeType = string | undefined;
Fixed!

2022-04-27 05:52 UTC, merged