Ft 12 composition tokens 473
six7/figma-tokens pull request #646
Opened 2022-04-28 05:05 UTC by swordEdge

2022-04-28 08:07 UTC, six7 requested changes
Bit of functional feedback:
- Can you use a Dropdown for the Property Picker? Like the Selector that appears when you Right click a token or when you click bottom left of the plugin? This would have better support and in this case we don't need the user to type in the property
<img width="185" alt="image" src="https://user-images.githubusercontent.com/4548309/165707129-9c9a6329-9159-4bdc-b751-07cc5d6e4678.png">

- I currently get an error when I try to open the Inspect panel and a composition token with 2 properties is applied 
<img width="436" alt="image" src="https://user-images.githubusercontent.com/4548309/165706384-44d33058-26a8-4964-af9f-555b2c1902d5.png">

2022-04-29 17:58 UTC, swordEdge commented
> * Can you use a Dropdown for the Property Picker? Like the Selector that appears when you Right click a token or when you click bottom left of the plugin? This would have better support and in this case we don't need the user to type in the property

In Jira board, It was supposed to use Autocomplete, so, Requirement of this task is changed?

> * I currently get an error when I try to open the Inspect panel and a composition token with 2 properties is applied

It's fixed.

2022-04-30 16:49 UTC, six7 commented
> In Jira board, It was supposed to use Autocomplete, so, Requirement of this task is changed? @six7 

Let's make sure to use the dropdown, yes. 👍

2022-05-07 01:18 UTC, LiamMartens requested changes

2022-05-07 01:18 UTC, LiamMartens commented on src/app/components/CompositionTokenForm.tsx
> +      setValue(internalEditToken.value.filter((_, i) => i !== index));
Could we just update this to `setValue((internalEditToken.value as (TokenBoxshadowValue | TokenCompositionValue)[]).filter((_, i) => i !== index));` to not have a typing error

2022-05-07 01:18 UTC, LiamMartens commented on src/app/components/EditTokenForm.tsx
> +        setInternalEditToken(prev => ({ ...prev, value: style }));
This appears to give a  typing error, can we fix that?

2022-05-07 01:18 UTC, LiamMartens commented on src/app/components/PropertySwitchMenu.tsx
> +import { styled, keyframes } from '@/stitches.config';
`keyframes` can be removed, it's unused

2022-05-07 01:18 UTC, LiamMartens commented on src/app/components/SelectableInput.tsx
> +  required: boolean
Can we remove `required` and `value` from the props? It doesn't look like they are being used

2022-05-07 01:18 UTC, LiamMartens commented on src/app/components/SelectableInput.tsx
> +  onChange: React.ChangeEventHandler<HTMLSelectElement>;
This typing is not aligned with `react-select` and is causing an error at the moment, can we fix that as well

2022-05-07 01:18 UTC, LiamMartens commented on src/app/components/TokenButton/TokenButton.tsx
> +      let tokensInCompositionToken: NodeTokenRefMap = {};
This can be `const`

2022-05-07 01:18 UTC, LiamMartens commented on src/app/components/TokenButton/TokenButton.tsx
> +        compositionToken?.rawValue.map((token) => {
Use `forEach` instead, were not returning anything

2022-05-07 01:18 UTC, LiamMartens commented on src/app/components/TokenButton/TokenButton.tsx
> +          tokensInCompositionToken[token.property] = 'delete';
These are also causing typing errors but Im not sure we can quickly fix those so leave these for now..

2022-05-07 01:18 UTC, LiamMartens commented on src/app/components/TokenTooltip/TokenTooltipContentValue.tsx
> +import { SingleCompositionToken, SingleToken, SingleTypographyToken } from '@/types/tokens';
This imported type is unused

2022-05-07 01:18 UTC, LiamMartens commented on src/hooks/useGetActiveState.ts
>          // @TODO: This no longer seems to work for color tokens as prop is always string?
This should return that value, so keep the `()`

2022-05-07 01:18 UTC, LiamMartens commented on src/plugin/pluginData.ts
> +import { TokenCompositionValue } from '@/types/values';
This is unused

2022-05-07 01:18 UTC, LiamMartens commented on src/plugin/pluginData.ts
> +      let newValuesOnNode = {};
Can we assign a type to this? `let newValuesOnNode: NodeTokenRefMap = {};`

2022-05-07 07:02 UTC, swordEdge commented on src/app/components/CompositionTokenForm.tsx
> +import { CompositionTokenSingleValue } from '@/types/propertyTypes';
fixed

2022-05-07 07:07 UTC, swordEdge commented on src/app/components/CompositionTokenForm.tsx
> +        <PropertySwitchMenu open={menuOpened} onOpenChange={() => setMenuOpened(!menuOpened)}>
fixed

2022-05-07 07:20 UTC, swordEdge commented on src/app/components/CompositionTokenForm.tsx
> +                  <PropertySwitchMenuRadioItem value={property} key={index} onSelect={() => onPropertySelected(property)}>
done

2022-05-07 07:28 UTC, swordEdge commented on src/app/components/CompositionTokenForm.tsx
> +            onClick={() => onRemove(index)}
done

2022-05-07 07:32 UTC, swordEdge commented on src/app/components/CompositionTokenForm.tsx
> +function SingleStyleInput({
done

2022-05-07 07:48 UTC, swordEdge commented on src/app/components/CompositionTokenForm.tsx
> +      setValue(internalEditToken.value.filter((_, i) => i !== index));
There is no typing error already. So I think I don't have to change this.

2022-05-07 08:14 UTC, swordEdge commented on src/app/components/PropertySwitchMenu.tsx
> +import { styled, keyframes } from '@/stitches.config';
done

2022-05-07 08:19 UTC, swordEdge commented on src/app/components/SelectableInput.tsx
> +  required: boolean
fixed. I removed SelectableInput.tsx cause It is not used anywhere.

2022-05-07 08:19 UTC, swordEdge commented on src/app/components/SelectableInput.tsx
> +  onChange: React.ChangeEventHandler<HTMLSelectElement>;
fixed. I removed SelectableInput.tsx cause It is not used anywhere.

2022-05-07 08:39 UTC, swordEdge commented on src/app/components/TokenButton/TokenButton.tsx
> +        compositionToken?.rawValue.map((token) => {
fixed

2022-05-07 08:39 UTC, swordEdge commented on src/app/components/TokenButton/TokenButton.tsx
> +      let tokensInCompositionToken: NodeTokenRefMap = {};
fixed

2022-05-07 08:40 UTC, swordEdge commented on src/app/components/TokenTooltip/TokenTooltipContentValue.tsx
> +import { SingleCompositionToken, SingleToken, SingleTypographyToken } from '@/types/tokens';
fixed

2022-05-07 08:40 UTC, swordEdge commented on src/hooks/useGetActiveState.ts
>          // @TODO: This no longer seems to work for color tokens as prop is always string?
fixed

2022-05-07 08:41 UTC, swordEdge commented on src/plugin/pluginData.ts
> +import { TokenCompositionValue } from '@/types/values';
fixed

2022-05-07 08:42 UTC, swordEdge commented on src/plugin/pluginData.ts
> +      let newValuesOnNode = {};
fixed

2022-05-07 09:55 UTC, swordEdge commented on src/app/components/TokenButton/TokenButton.tsx
> +          tokensInCompositionToken[token.property] = 'delete';
fixed.

2022-05-07 09:55 UTC, swordEdge commented on src/app/components/CompositionTokenForm.tsx
> +  const propertiesMenu = React.useMemo(() => {
fixed

2022-05-07 09:56 UTC, swordEdge commented on src/app/components/EditTokenForm.tsx
> +        setInternalEditToken(prev => ({ ...prev, value: style }));
fixed

2022-05-08 22:23 UTC, LiamMartens approved these changes

2022-05-10 22:29 UTC, six7 approved these changes

2022-05-10 22:29 UTC, merged