Optimize tokens
six7/figma-tokens pull request #655
Opened 2022-04-30 22:54 UTC by six7

2022-04-30 23:21 UTC, six7 commented on src/app/components/TokenListing.tsx
> +            data-cy="button-add-new-token"
```suggestion
            dataCy="button-add-new-token"
```

2022-04-30 23:21 UTC, six7 commented on src/app/components/TokenTree.tsx
>                      data-cy="button-add-new-token-in-group"
```suggestion
                    dataCy="button-add-new-token-in-group"
```

2022-05-01 00:05 UTC, LiamMartens requested changes

2022-05-01 00:05 UTC, LiamMartens commented on src/app/components/ImportedTokensDialog.tsx
> +  const handleSetUpdatedTokens = React.useCallback((tokens: SingleToken[]) => {
@six7 good to see useCallbacks! :smile:

2022-05-01 00:05 UTC, LiamMartens commented on src/app/components/ImportedTokensDialog.tsx
> +                updateToken={handleCreateSingleClick(token)}
Did you mean to write these like this? Now the handlers will be executed on render, which presumably is not the intention. The handlers itself should just use the `token` and `newTokens` variables and then you can just pass the functions into the props as is `removeToken={handleSetewTokens}`.

2022-05-01 00:05 UTC, LiamMartens commented on src/app/components/ImportedTokensDialog.tsx
> +                removeToken={handleSetUpdatedTokens(updatedTokens.filter((t) => t.name !== token.name))}
Same thing as above

2022-05-01 08:21 UTC, six7 commented on src/app/components/ImportedTokensDialog.tsx
> +                updateToken={handleCreateSingleClick(token)}
Thanks, hope I got that right with this one. The handler itself now uses the token, however I still have to pass the current token in, like this:

```
  const handleIgnoreExistingToken = React.useCallback((token) => () => {
    setUpdatedTokens((updatedTokens.filter((t) => t.name !== token.name)));
  }, [setUpdatedTokens, updatedTokens]);

  ...
  removeToken={handleIgnoreExistingToken(token)}
```

2022-05-01 13:03 UTC, LiamMartens requested changes

2022-05-01 13:03 UTC, LiamMartens commented on src/app/components/ImportedTokensDialog.tsx
> +                updateToken={handleCreateSingleClick(token)}
Then this actually needs to be separated into it's own component taking the `token` as a prop. Then you can create handlers with those tokens specifically.

2022-05-01 14:53 UTC, six7 commented on src/app/components/ImportedTokensDialog.tsx
> +                updateToken={handleCreateSingleClick(token)}
Got it, fixed in newest commit. 🙏

2022-05-04 01:08 UTC, LiamMartens approved these changes
@six7 just one small comment - other than that good to go

2022-05-04 01:08 UTC, LiamMartens commented on src/types/tokens/ImportToken.ts
> +export type ImportToken = SingleToken & {
Could you just change this with
```
export type ImportToken<Named = true> = SingleToken<Named, {
  oldValue?: string;
  oldDescription?: string;
}>
```

Keeps the typing more strict

2022-05-04 02:46 UTC, merged