add renametokengroup function
six7/figma-tokens pull request #662
Opened 2022-05-02 13:01 UTC by MightyDevKnight

2022-05-02 20:27 UTC, LiamMartens requested changes

2022-05-02 20:27 UTC, LiamMartens commented on src/app/components/TokenGroupHeading.tsx
> +      <Modal isOpen={showNewGroupNameField} close={() => setShowNewGroupNameField(false)}>
Could these handlers be moved to `useCallback`

2022-05-02 20:27 UTC, LiamMartens commented on src/app/components/TokenGroupHeading.tsx
> +          <Heading size="small">Rename {path.split('.').pop()}</Heading>
Should probably memo this heading label, the `split` operation will create a new array each render cycle

2022-05-02 20:27 UTC, LiamMartens commented on src/app/components/TokenGroupHeading.tsx
> +                onChange={(e) => setNewTokenGroupName(e.target.value)}
same about the callback

2022-05-02 20:27 UTC, LiamMartens commented on src/app/components/TokenGroupHeading.tsx
> +                defaultValue={path.split('.').pop() || ''}
Same about memoizing it - especially since we are using it multiple times

2022-05-03 14:18 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +      <Modal isOpen={showNewGroupNameField} close={() => setShowNewGroupNameField(false)}>
Done.

2022-05-03 14:19 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +      <Modal isOpen={showNewGroupNameField} close={() => setShowNewGroupNameField(false)}>
Done.

2022-05-03 14:19 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +      <Modal isOpen={showNewGroupNameField} close={() => setShowNewGroupNameField(false)}>
Done.

2022-05-03 14:19 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +      <Modal isOpen={showNewGroupNameField} close={() => setShowNewGroupNameField(false)}>
Done.

2022-05-03 14:19 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +      <Modal isOpen={showNewGroupNameField} close={() => setShowNewGroupNameField(false)}>
Done.

2022-05-03 14:19 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +                defaultValue={path.split('.').pop() || ''}
Done.

2022-05-03 14:20 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +                onChange={(e) => setNewTokenGroupName(e.target.value)}
Done.

2022-05-03 14:20 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +          <Heading size="small">Rename {path.split('.').pop()}</Heading>
Done.

2022-05-04 15:15 UTC, LiamMartens requested changes

2022-05-04 15:15 UTC, LiamMartens commented on src/app/components/TokenGroupHeading.tsx
> +      <Modal isOpen={showNewGroupNameField} close={() => handleSetNewTokenGroupNameFileClose}>
This should just be `<Modal isOpen={showNewGroupNameField} close={handleSetNewTokenGroupNameFileClose}>`

2022-05-04 15:15 UTC, LiamMartens commented on src/app/components/TokenGroupHeading.tsx
> +                onChange={(e) => handleNewTokenGroupNameChange(e)}
This should be `onChange={handleNewTokenGroupNameChange}`

2022-05-06 20:37 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +      <Modal isOpen={showNewGroupNameField} close={() => handleSetNewTokenGroupNameFileClose}>
Done

2022-05-06 20:37 UTC, MightyDevKnight commented on src/app/components/TokenGroupHeading.tsx
> +                onChange={(e) => handleNewTokenGroupNameChange(e)}
Done

2022-05-08 22:27 UTC, LiamMartens approved these changes

2022-05-12 06:06 UTC, closed without merging