Ft 46 autocomplete add to remap and all token inputs
six7/figma-tokens pull request #673
Opened 2022-05-04 06:51 UTC by swordEdge

2022-05-06 10:01 UTC, six7 requested changes
Bit of functional feedback:

- I think we need to change how the Autocomplete works. With this current implementation it's possible e.g. in a typography token to open up the popover multiple times, leading to a bad ux. We don't need to address this in this branch, but should do a followup soon after.
<img width="504" alt="image" src="https://user-images.githubusercontent.com/4548309/167110551-af2df4fe-9f9a-45ea-b436-2c1dede2a019.png">

- For typography tokens and shadow tokens it currently show [object Object] as a value. It would probably be good to show the shorthand (the one we also show in the tooltip) here. Maybe we can abstract that so we can use the same shorthand in both this alias value and this autocomplete.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/4548309/167110511-5f7c1f50-78cb-4c2b-b823-85e46d816ca5.png">

2022-05-08 18:59 UTC, swordEdge commented
> With this current implementation it's possible e.g. in a typography token to open up the popover multiple times, leading to a bad ux

I tried to open up the popover multiple times but there was no bad ux error similar to yours. I think it was already fixed.


> For typography tokens and shadow tokens it currently show [object Object] as a value. It would probably be good to show the shorthand

done

2022-05-11 19:36 UTC, LiamMartens requested changes

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/DownshiftInput.tsx
> +  const resolveValue = useCallback((token: SingleToken) => {
There's no need to mutate `acc` when reducing since the returned value will be the next value anyways. This block also gives ESLint errors anyways - make sure you have ESLint enabled in your VS Code.

```
      if (Array.isArray(token.value)) {
        returnValue = token.value.reduce<string>((totalAcc, item) => {
          const singleReturnValue = Object.entries(item).reduce<string>((acc, [,value]) => (
            `${acc}${value.toString()}/`
          ), '');
          return `${totalAcc}${singleReturnValue},`;
        }, '');
      } else {
        returnValue = Object.entries(token.value).reduce<string>((acc, [,value]) => (
          `${acc}${value.toString()}/`
        ), '');
      }
```

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/InspectorTokenSingle.tsx
>  export default function InspectorTokenSingle({
A few ESLint errors on this file, but they are auto-fixable. Can you just format it using ESLint

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/InspectorTokenSingle.tsx
> +  }, [showDialog]);
It's not necessary to specify `showDialog` itself as a dependency here as it's not being used. Same with the other callbacks, you only need to specify the variables you actually use within the function body

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/SingleBoxShadowInput.tsx
> +import React from 'react';
Same here, please format it with ESLint

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/SingleBoxShadowInput.tsx
> +  const changeAutoSuggest = React.useCallback((index: number) => {
Can you move the `changeAutoSuggest` function before the `handleAutoSuggest` one. The definition order is now incorrect.

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/SingleBoxShadowInput.tsx
> +  const closeAutoSuggest = React.useCallback((index: number) => {
Same here, order should be changed

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/SingleBoxShadowInput.tsx
> +                setInputValue={(newInputValue: string) => handleBoxshadowDownShiftInputChange(newInputValue, key)}
Can we make a useCallback for this? It would mean seperating this into a new file.
Now it does give an ESlint error

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/TypographyInput.tsx
> +import React from 'react';
Same thing, please run the ESLint formatter

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/TypographyInput.tsx
> +  const handleAutoSuggest = React.useCallback((keyIndex: number) => (() => changeAutoSuggest(keyIndex)), [showAutoSuggest]);
Also same comment here, the order of these functions need to be fixed so they get declared correctly.

2022-05-11 19:36 UTC, LiamMartens commented on src/app/components/TypographyInput.tsx
> +              setInputValue={(newInputValue: string) => handleTypographyDownShiftInputChange(newInputValue, key)}
And same comment here - please make a useCallback for this, or you could also useMemo the whole map and then Im happy to eslint ignore the callback

2022-05-12 00:57 UTC, swordEdge commented on src/app/components/InspectorTokenSingle.tsx
> +  }, [showDialog]);
fixed

2022-05-12 01:35 UTC, swordEdge commented on src/app/components/DownshiftInput.tsx
> +  const resolveValue = useCallback((token: SingleToken) => {
fixed

2022-05-12 02:31 UTC, swordEdge commented on src/app/components/InspectorTokenSingle.tsx
>  export default function InspectorTokenSingle({
fixed

2022-05-12 02:31 UTC, swordEdge commented on src/app/components/InspectorTokenSingle.tsx
> +  }, [showDialog]);
fixed

2022-05-12 02:32 UTC, swordEdge commented on src/app/components/SingleBoxShadowInput.tsx
> +import React from 'react';
fixed

2022-05-12 02:32 UTC, swordEdge commented on src/app/components/SingleBoxShadowInput.tsx
> +  const changeAutoSuggest = React.useCallback((index: number) => {
fixed

2022-05-12 02:32 UTC, swordEdge commented on src/app/components/SingleBoxShadowInput.tsx
> +  const closeAutoSuggest = React.useCallback((index: number) => {
fixed

2022-05-12 02:33 UTC, swordEdge commented on src/app/components/TypographyInput.tsx
> +import React from 'react';
fixed

2022-05-12 02:33 UTC, swordEdge commented on src/app/components/TypographyInput.tsx
> +  const handleAutoSuggest = React.useCallback((keyIndex: number) => (() => changeAutoSuggest(keyIndex)), [showAutoSuggest]);
fixed

2022-05-12 08:34 UTC, swordEdge commented on src/app/components/SingleBoxShadowInput.tsx
> +                setInputValue={(newInputValue: string) => handleBoxshadowDownShiftInputChange(newInputValue, key)}
done

2022-05-12 08:34 UTC, swordEdge commented on src/app/components/TypographyInput.tsx
> +              setInputValue={(newInputValue: string) => handleTypographyDownShiftInputChange(newInputValue, key)}
done

2022-05-13 06:10 UTC, six7 requested changes

2022-05-13 06:10 UTC, six7 commented on src/app/components/InspectorTokenSingle.tsx
> +  const handleDownShiftInputChange = React.useCallback((newInputValue: string) => {
Can we make sure to just 1 component for DownshiftInput and not have the logic spread throughout the app? This should all be part of the downshiftinput Component ideally

2022-05-13 06:10 UTC, six7 commented on src/app/components/InspectorTokenSingle.tsx
> +  const handleToggleInputHelper = React.useCallback(() => {
I'd love to have the downshift component itself handle the logic of when the popover is open or not

2022-05-13 06:10 UTC, six7 commented on src/app/components/InspectorTokenSingle.tsx
> +                            style={{ background: newTokenName, fontSize: 0 }}
We cant use specific color values anymore since we have dark mode support. We need to use tokens eg $borderMuted as that value will adapt when user has dark mode active

2022-05-13 06:10 UTC, six7 commented on src/app/components/SingleBoxShadowInput.tsx
> +const propertyTypes = {
This is duplicative of the prop being used in the other component above, cant we combine that?

2022-05-13 06:10 UTC, six7 commented on src/app/components/SingleBoxShadowInput.tsx
> +  const [showAutoSuggest, setShowAutoSuggest] = React.useState<Array<boolean>>(defalutShowAutoSuggest);
I'd really prefer to have all the autosuggeat logic living inside the DownShiftInput component and not spread around so many components. That component should be responsible for open/close state, current value etc.

Right now i noticed you have duplicated that logic to many parts when it would only need to be living in 1 component

2022-05-13 06:10 UTC, six7 commented on src/app/components/TypographyInput.tsx
> +  const changeAutoSuggest = React.useCallback((index: number) => {
Same here, can we move all that into the 1 DownshiftInput.tsx ? It should really only live in 1 place

2022-05-13 06:10 UTC, six7 commented on src/app/components/TypographyInput.tsx
> +    newShowAutoSuggest[index] = !newShowAutoSuggest[index];
Also we dont need multiple of these being open at the same time

2022-05-14 07:03 UTC, swordEdge commented on src/app/components/InspectorTokenSingle.tsx
> +  const handleDownShiftInputChange = React.useCallback((newInputValue: string) => {
DownShiftInput component is used in several components including EditTokenForm. In other components, we expect DownShiftInput to return alias value because it will be resolved using getAliasValue e.g {size.0} => 0.
But in InspectorTokenSingle, we expect name to be returned because we use getTokenValue not getAliasValue. e.g: size.0 => 0.
So we have to deal with alias case in handleDownShiftInputChange function or mappedToken.

2022-05-14 07:28 UTC, swordEdge commented on src/app/components/InspectorTokenSingle.tsx
> +  const handleToggleInputHelper = React.useCallback(() => {
This function handles the visibility of the ColorPicker panel which is out of the DownShiftInput. I think it's better to handle it here.

2022-05-14 15:15 UTC, six7 requested changes
i also noticed the scroll is off for box shadows as well. can we please make it so that the scroll occurs in the popover, not the whole modal?

in this video there's also the thing where we're able to open up the popover multiple times. i'd like to solve this, but i feel this requires a refactor of the whole component to something where clicking outside closes the popover. feel free to do this in a followup branch.

https://user-images.githubusercontent.com/4548309/168434148-78356bc3-84cc-482c-8e2d-52aa158ce686.mp4

2022-05-14 15:15 UTC, six7 commented on src/app/components/InspectorTokenSingle.tsx
> +  const handleToggleInputHelper = React.useCallback(() => {
but why do we need a colorpicker in inspect?? inspect should only allow you to choose a different token, not specify a value.

edit: i've checked out the plugin and it seems there was a miscommunication here.

we're not supposed to add a fully functional token input to the Inspector Remap. instead it should just allow you to pick another token only, not specify the value of the token. there's no need for a color picker or the user to enter a token value. theyre supposed to pick another token only.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/4548309/168432114-93ddd725-6462-4640-9643-5be121216c63.png">

2022-05-14 15:15 UTC, six7 commented on src/app/components/InspectorTokenSingle.tsx
> +  const handleToggleInputHelper = React.useCallback(() => {
some other things i noticed:

- sometimes it doesnt give me any results. i applied a spacing token for gap (property itemSpacing), but it doesnt show me any results. if i change it to `all` it shows me results.

- i also noticed that the scroll is kind of broken in this one. it should just scroll the tokens, not the whole modal.


https://user-images.githubusercontent.com/4548309/168432820-aa9fec8c-2160-4175-b25e-d5f8fc2a68af.mp4

2022-05-18 07:03 UTC, six7 approved these changes

2022-05-18 07:04 UTC, merged