Ft 16 losing tokens when plugin restarts
six7/figma-tokens pull request #678
Opened 2022-05-06 03:02 UTC by swordEdge

2022-05-08 22:31 UTC, LiamMartens approved these changes

2022-05-13 06:50 UTC, six7 requested changes

2022-05-13 06:50 UTC, six7 commented on src/app/components/App.test.tsx
> -  it('skip to token screen when there is a token', () => {
Can we make sure to still keep this test that the loading screen advances by itself when tokens are found? You removed this and added a cancel click but both cases need to work

2022-05-13 06:50 UTC, six7 commented on src/app/components/Initiator.tsx
> +    const shouldPull = await confirm({
Its not just github users can pull from, its depending on what provider they have. Jsonbin, github, gitlab, azure devops

2022-05-13 06:50 UTC, six7 commented on src/app/components/Initiator.tsx
> -                notifyToUI('Failed to fetch tokens, check your credentials', { error: true });
Did you remove that and move it somewhere else? Cant find it anymore. This is to tell the user that we were unable to fetch

2022-05-13 06:50 UTC, six7 commented on src/app/store/updateSources.tsx
> +  checkForChanges: string
This should give an eslint error and be autofixable

2022-05-13 06:50 UTC, six7 commented on src/types/tokens/TokensStore.ts
> +  values: Record<string, AnyTokenList>
Same, should give eslint error

2022-05-14 15:42 UTC, six7 commented
functionally this works fine! if you could merge `next` back in, we had some changes with release-99 that touched the same files i believe. once merged next and confirmed working we can merge it

2022-05-18 07:08 UTC, six7 commented
@swordEdge once you fix the failing test we can merge

2022-05-18 10:53 UTC, merged