Ft 63 gh optimize startup with a loading screen
six7/figma-tokens pull request #679
Opened 2022-05-06 03:27 UTC by swordEdge

2022-05-06 09:52 UTC, six7 requested changes

2022-05-06 09:52 UTC, six7 commented on src/app/components/App.test.tsx
> +    const LodingText = getByText('Loading. please wait');
```suggestion
    const LoadingText = getByText('Loading. please wait');
```

2022-05-06 09:52 UTC, six7 commented on src/app/components/App.test.tsx
> +    expect(LodingText).toBeInTheDocument();
```suggestion
    expect(LoadingText).toBeInTheDocument();
```

2022-05-06 09:52 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +const lodingStyle = {
can you change the raw hex values to tokens? You can introduce new tokens in stitches.config. I'd suggest `bgLoadingScreen` and `fgLoadingScreen` and other variations instead of using raw values here

2022-05-06 09:52 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +    <Stack direction="column" gap={4} css={{...lodingStyle}}>
```suggestion
    <Stack direction="column" gap={4} css={{...loadingStyle}}>
```

2022-05-06 09:52 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +          <img alt="Figma" src={require('../assets/mark.png')} className="rounded width-13w"/>
can you change these to SVGs? I'll attach them here:

```
<svg width="144" height="145" viewBox="0 0 144 145" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M44.7937 69.2106C31.9652 69.0998 21.6 58.6661 21.6 45.8115C21.6 32.888 32.0765 22.4115 45 22.4115C57.8432 22.4115 68.2698 32.7584 68.3988 45.5711C68.3996 45.628 68.4 45.685 68.4 45.7421V57.5806C68.4 64.0041 63.1927 69.2114 56.7692 69.2114H45.0688C45.0459 69.2114 45.0229 69.2115 45 69.2115C44.977 69.2115 44.9541 69.2114 44.9311 69.2114H44.9308C44.885 69.2114 44.8393 69.2111 44.7937 69.2106Z" fill="currentColor"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M101.259 72.8067C112.977 72.5622 122.4 62.9873 122.4 51.2115C122.4 39.2821 112.729 29.6115 100.8 29.6115C89.0271 29.6115 79.4541 39.0301 79.205 50.7432C79.2016 50.8527 79.2 50.9626 79.2 51.0729V62.1499C79.2 68.0381 83.9733 72.8114 89.8615 72.8114H100.753C100.769 72.8114 100.784 72.8115 100.8 72.8115C100.816 72.8115 100.831 72.8114 100.847 72.8114H100.938C101.046 72.8114 101.153 72.8098 101.259 72.8067Z" fill="currentColor"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M72.3637 103.023C72.3612 103.152 72.36 103.282 72.36 103.411C72.36 114.347 81.2248 123.211 92.16 123.211C103.095 123.211 111.96 114.347 111.96 103.411C111.96 92.4762 103.095 83.6115 92.16 83.6115C92.0293 83.6115 91.8989 83.6127 91.7688 83.6152C91.675 83.6128 91.5809 83.6115 91.4865 83.6115H82.9334C77.0939 83.6115 72.36 88.3454 72.36 94.185V102.738C72.36 102.833 72.3612 102.928 72.3637 103.023Z" fill="currentColor"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M61.541 97.178C61.5536 97.4542 61.56 97.7321 61.56 98.0114C61.56 107.953 53.5011 116.011 43.56 116.011C33.6189 116.011 25.56 107.953 25.56 98.0114C25.56 88.0703 33.6189 80.0114 43.56 80.0114C43.8393 80.0114 44.1172 80.0178 44.3934 80.0304C44.6032 80.0179 44.8147 80.0115 45.0276 80.0115H51.0922C56.8734 80.0115 61.5599 84.698 61.5599 90.4792V96.5438C61.5599 96.7567 61.5536 96.9682 61.541 97.178Z" fill="currentColor"/>
</svg>
```

```
<svg width="228" height="97" viewBox="0 0 228 97" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M30.1316 44.3838V33.2927L51.1082 31.983V22.6184L30.1316 23.9282V10.6999H52.5504V1.46633H19.5777V47.6342L30.1316 44.3838Z" fill="currentColor"/>
<path d="M67.4286 11.2893C71.2962 11.2893 73.7216 9.45567 73.7216 6.05037C73.7216 2.71057 71.2962 0.811462 67.4286 0.811462C63.5611 0.811462 61.2668 2.71057 61.2668 6.05037C61.2668 9.45567 63.5611 11.2893 67.4286 11.2893ZM82.7678 47.6342V38.4007H73.3939V19.4096C73.3939 15.7424 71.3618 13.7123 67.6253 13.9087L55.1704 14.5636V23.7972L63.2333 23.4043V38.4007H53.8594V47.6342H82.7678Z" fill="currentColor"/>
<path d="M121.634 14.5636C118.684 14.5636 115.209 14.891 113.243 17.445C109.769 14.891 105.18 13.9087 100.132 13.9087C89.7097 13.9087 81.4501 18.0999 81.4501 26.8096C81.4501 37.6803 94.2983 39.3829 106.425 35.1263V37.7458C100.329 39.1865 93.5117 39.9723 85.9732 40.6927L87.0876 46.6519C97.2482 44.9493 109.113 42.7882 109.113 47.6342C109.113 51.236 105.049 51.4979 83.6133 51.4979V60.7315C108.195 60.7315 119.733 59.6182 119.733 49.8608C119.733 42.8537 112.653 40.8891 105.18 41.3475C114.226 38.2697 120.126 34.3405 120.126 28.1193C120.126 26.3512 119.601 24.845 119.208 24.3211C120.126 23.7972 121.306 23.7972 122.289 23.7972H124.518V14.5636H121.634ZM100.788 31.7865C94.495 31.7865 92.004 30.2803 92.004 27.4644C92.004 24.714 94.495 23.0768 100.788 23.0768C107.081 23.0768 109.572 24.714 109.572 27.4644C109.572 30.2803 107.081 31.7865 100.788 31.7865Z" fill="currentColor"/>
<path d="M173.423 13.9087C166.999 13.9087 164.049 17.9034 162.738 23.7972H160.837C159.854 18.0344 157.232 13.9087 151.004 13.9087C144.58 13.9087 141.565 17.9034 140.254 23.7972H137.566L139.598 17.9034V14.5636H129.044V47.6342H139.598V36.0431C139.598 28.0538 140.844 23.1423 146.547 23.1423C150.414 23.1423 151.463 24.845 151.463 31.1317V47.6342H162.017V36.0431C162.017 28.0538 163.263 23.1423 168.966 23.1423C172.833 23.1423 173.882 24.845 173.882 31.1317V47.6342H184.436V30.4113C184.436 21.5052 181.879 13.9087 173.423 13.9087Z" fill="currentColor"/>
<path d="M188.996 38.5971C188.996 42.0024 190.766 48.2891 201.058 48.2891C210.301 48.2891 213.513 43.6396 214.758 38.1387H217.38L215.742 42.0679V42.7228C215.742 45.8661 217.512 47.6342 220.658 47.6342H228V38.4007H223.215V29.1671C223.215 18.2963 215.152 13.9087 206.04 13.9087C196.797 13.9087 189.652 18.8202 189.652 27.2025H199.55C199.55 24.1901 201.845 22.4875 206.04 22.4875C210.563 22.4875 212.661 24.0591 212.661 26.7441L202.238 28.1848C192.405 29.56 188.996 32.8998 188.996 38.5971ZM199.55 36.6325C199.55 34.7334 201.124 34.275 204.205 33.8166L212.661 32.6378C212.661 36.698 208.859 39.121 203.156 39.121C201.386 39.121 199.55 38.5316 199.55 36.6325Z" fill="currentColor"/>
<path d="M18.4201 71.6909H29.3018V62.4573H18.4201V52.9618L7.86625 56.2361V62.4573H0V71.6909H7.86625V90.6164C7.86625 94.2182 9.83281 96.3137 13.4382 96.1828L30.6128 95.5279V86.2943L18.4201 86.9492V71.6909Z" fill="currentColor"/>
<path d="M33.2062 78.9599C33.2062 90.5509 41.4658 96.1828 51.8885 96.1828C62.2458 96.1828 70.5053 90.5509 70.5053 78.9599C70.5053 67.4342 62.2458 61.8024 51.8885 61.8024C41.4658 61.8024 33.2062 67.4342 33.2062 78.9599ZM43.7601 78.9599C43.7601 73.459 46.9066 71.036 51.8885 71.036C56.8049 71.036 60.017 73.459 60.017 78.9599C60.017 84.5262 56.8049 86.9492 51.8885 86.9492C46.9066 86.9492 43.7601 84.5262 43.7601 78.9599Z" fill="currentColor"/>
<path d="M112.483 95.5279L101.274 78.5669L106.387 76.2094C109.271 74.8342 110.517 72.8041 110.517 69.6608V62.4573H99.9628L100.094 68.4165L85.0169 75.3581V51.4883H74.463V95.5279H85.0169V86.1634L92.2932 82.7581L100.487 95.5279H112.483Z" fill="currentColor"/>
<path d="M113.162 78.5669C113.162 87.9315 118.996 96.1828 131.713 96.1828C143.185 96.1828 148.691 88.6518 149.281 83.8713H138.793C138.137 86.3598 135.384 87.6695 131.713 87.6695C125.748 87.6695 123.06 84.9846 123.06 81.1864H148.101V77.9121C148.101 67.8927 140.89 61.8024 130.599 61.8024C120.307 61.8024 113.162 68.0891 113.162 78.5669ZM123.06 75.2926C123.06 72.8041 124.764 70.3811 130.599 70.3811C136.433 70.3811 138.268 72.8041 138.268 75.2926H123.06Z" fill="currentColor"/>
<path d="M173.77 71.036C178.818 71.036 180.588 73.328 180.588 79.2873V95.5279H191.142V77.6501C191.142 67.4342 186.029 61.8024 177.572 61.8024C170.493 61.8024 166.363 66.452 165.052 72.3457H162.364L164.396 66.452V62.4573H153.842V95.5279H164.396V83.282C164.396 73.9829 168.133 71.036 173.77 71.036Z" fill="currentColor"/>
<path d="M227.289 86.4253C227.289 79.5492 221.39 77.9121 214.966 75.8165C209.721 74.1139 206.444 73.1316 206.444 71.5599C206.444 70.2502 207.755 69.6608 210.246 69.6608C213.851 69.6608 215.621 71.4289 215.621 73.7864H226.175C226.175 67.3688 221.521 61.8024 210.311 61.8024C201.2 61.8024 195.89 65.2077 195.89 71.1015C195.89 78.5014 203.428 80.1386 209.59 82.1687C214.9 83.9368 216.736 84.3952 216.736 86.0979C216.736 87.6695 214.966 88.3244 212.147 88.3244C206.641 88.3244 204.936 86.0979 204.936 83.5439H194.382C194.382 91.2713 199.626 96.1828 211.819 96.1828C223.225 96.1828 227.289 91.9916 227.289 86.4253Z" fill="currentColor"/>
</svg>
```

2022-05-06 09:52 UTC, six7 commented on src/app/components/StartScreen.tsx
> +    <div className="h-auto p-4 my-auto overflow-auto">
```suggestion
    <div className="h-auto p-4 my-auto content scroll-container">
```

this just adds the correct styling

2022-05-06 09:52 UTC, six7 commented on src/app/styles/tailwind.css
> +.width-30w {
can you convert this to use Stitches instead? We're in the process of removing tailwind so let's not add any new classes here.

2022-05-06 10:01 UTC, six7 requested changes
One more thing: Can we hide the Footer while the startscreen is showing?

2022-05-06 17:14 UTC, swordEdge commented on src/app/components/App.test.tsx
> +    const LodingText = getByText('Loading. please wait');
fixed

2022-05-06 17:14 UTC, swordEdge commented on src/app/components/App.test.tsx
> +    expect(LodingText).toBeInTheDocument();
fixed

2022-05-06 17:14 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +const lodingStyle = {
fixed

2022-05-06 17:14 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +    <Stack direction="column" gap={4} css={{...lodingStyle}}>
fixed

2022-05-06 17:14 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +          <img alt="Figma" src={require('../assets/mark.png')} className="rounded width-13w"/>
done

2022-05-06 17:14 UTC, swordEdge commented on src/app/components/StartScreen.tsx
> +    <div className="h-auto p-4 my-auto overflow-auto">
fixed

2022-05-06 17:14 UTC, swordEdge commented on src/app/styles/tailwind.css
> +.width-30w {
done

2022-05-06 20:44 UTC, six7 requested changes

2022-05-06 20:44 UTC, six7 commented on src/app/components/icons/IconFigmaLetter.tsx
> +import React from 'react';
Can you add these just as .svg? This icon implementation is an old one, you can just import svgs nowadays. If you search code for an svg's you'll see how those are implemented

2022-05-06 20:44 UTC, six7 commented on src/app/components/Footer.tsx
> +        {(localApiState.branch && activeTab !== 'loading' && activeTab !== 'start') && (
This condition only covered the branch picker, we dont want to show the whole footer when in Loading screen

2022-05-06 20:44 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +const FgLoadingScreen = styled('div', {
What i meant was not the name of this const but the colors being used

2022-05-06 20:44 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +  background: 'Black',
```suggestion
  background: '$bgLoadingScreen',
```

2022-05-06 20:44 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +  color: 'White',
```suggestion
  color: '$fgLoadingScreen',
```

2022-05-06 20:44 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +    color: 'wheat',
```suggestion
    color: '$fgLoadingScreen',
```

2022-05-06 20:44 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +  '& > div > button:hover': {
To have better specificity you can directly target another stitches component, this would be less prone to break in the future

2022-05-06 20:44 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +    background: 'black !important'
Is this required?

2022-05-06 20:44 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +    filter: 'invert(99%) sepia(4%) saturate(2476%) hue-rotate(86deg) brightness(118%) contrast(119%)'
You can color the spinner by just specifying
```suggestion
    color: '$fgLoadingScreen'
```

2022-05-06 20:44 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +          <div className="rotate">
If you specify color in here for the spinner you dont need to do it in the styled block

2022-05-06 20:44 UTC, six7 commented on src/app/components/App.tsx
> -      <LoadingBar />
This seems like a mistake. We do want to keep the loading bar, as its being used throughout the plugin (we just dont want to use it in the loading screen)

2022-05-07 05:04 UTC, swordEdge commented on src/app/components/App.tsx
> -      <LoadingBar />
fixed.

2022-05-07 05:53 UTC, swordEdge commented on src/app/components/icons/IconFigmaLetter.tsx
> +import React from 'react';
done

2022-05-07 05:56 UTC, swordEdge commented on src/app/components/Footer.tsx
> +        {(localApiState.branch && activeTab !== 'loading' && activeTab !== 'start') && (
done

2022-05-07 05:56 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +const FgLoadingScreen = styled('div', {
done

2022-05-07 05:58 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +  background: 'Black',
done

2022-05-07 05:58 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +  color: 'White',
done

2022-05-07 06:13 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +  '& > div > button:hover': {
done

2022-05-07 06:26 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +    background: 'black !important'
hover selector is required to notify the user that the mouse is over.

2022-05-07 06:27 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +    color: 'wheat',
done

2022-05-07 06:35 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +    filter: 'invert(99%) sepia(4%) saturate(2476%) hue-rotate(86deg) brightness(118%) contrast(119%)'
The problem is that the **color** attribute doesn't seem to work to change the spinner color. Now default loading spinner is defined as black in the `IconLoading.txs` SVG file. If you don't like filter attr to change color, I think we need to create another SVG to define color as white.

2022-05-07 06:42 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +          <div className="rotate">
done

2022-05-07 09:36 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +    filter: 'invert(99%) sepia(4%) saturate(2476%) hue-rotate(86deg) brightness(118%) contrast(119%)'
Lets do this then: change the spinner color on the svg from black to 'currentColor' as in all the other svg's. Then it will be able to pick up the color attribute, no need for a second svg then.

2022-05-07 12:53 UTC, six7 commented on src/app/components/FigmaLoading.tsx
> +          <div className="rotate">
did you push your most recent commit? can't see changes

2022-05-07 17:55 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +    filter: 'invert(99%) sepia(4%) saturate(2476%) hue-rotate(86deg) brightness(118%) contrast(119%)'
done. I removed initial-loading.svg.

2022-05-07 17:57 UTC, swordEdge commented on src/app/components/FigmaLoading.tsx
> +          <div className="rotate">
done. The previous pr, I created a new SVG for spinner color so I didn't need to style it here.

2022-05-09 00:16 UTC, swordEdge commented
> One more thing: Can we hide the Footer while the startscreen is showing?
done

2022-05-09 06:41 UTC, six7 commented
@swordEdge there's a failing cypress test. the other failing test can be fixed by updating to the latest `next` branch.

2022-05-09 12:46 UTC, swordEdge commented
> @swordEdge there's a failing cypress test. the other failing test can be fixed by updating to the latest `next` branch.

done

2022-05-09 20:47 UTC, six7 approved these changes

2022-05-09 20:48 UTC, six7 approved these changes

2022-05-09 20:49 UTC, merged