Ft 151 composition tokens pt ii
six7/figma-tokens pull request #730
Opened 2022-05-20 13:47 UTC by swordEdge

2022-05-21 08:07 UTC, six7 requested changes
Added some comments. Overall great!

2022-05-21 08:07 UTC, six7 commented on src/app/components/SingleCompositionTokenForm.tsx
> +          <DropdownMenuContent sideOffset={2} className="content scroll-container" css={{ maxHeight: '$11', backgroundColor: '$bgDefault', color: '$text' }}>
```suggestion
          <DropdownMenuContent sideOffset={2} className="content scroll-container" css={{ maxHeight: '$dropdownMaxHeight' }}>
```

No need to specify bgColor, the dropdown handles this for us. Also I changed name of token to be descriptive.

2022-05-21 08:07 UTC, six7 commented on src/stitches.config.ts
> +      11: '140px',
```suggestion
```

This token is only required in `sizing`

2022-05-21 08:07 UTC, six7 commented on src/stitches.config.ts
> +      11: '140px',
```suggestion
      dropdownMaxHeight: '170px',
```

2022-05-21 08:07 UTC, six7 commented on src/app/components/SingleCompositionTokenForm.tsx
> +            <span>{property}</span>
```suggestion
          <DropdownMenuTrigger bordered css={{ flex: 3, minHeight: '$10' }}>
            <span>{property || "Choose a property"}</span>
```

2022-05-23 17:00 UTC, six7 approved these changes

2022-05-23 22:23 UTC, LiamMartens requested changes

2022-05-23 22:23 UTC, LiamMartens commented on src/types/CompositionTokenProperty.ts
> +Record<TokenTypes, string | number | object | Array<TokenBoxshadowValue>>
Do not use `object`, please type it fully. `object` is too vague.

2022-05-23 22:23 UTC, LiamMartens commented on src/types/CompositionTokenProperty.ts
> +import { Properties } from "@/constants/Properties";
I see this is using double quotes, make sure you let eslint fix any errors before committing. Secondly, also make sure `eslint` is installed and enabled in VSCode.

2022-05-23 22:23 UTC, LiamMartens commented on src/utils/alias/checkIfContainsAlias.tsx
> +export function checkIfContainsAlias(token?: string | number | object | null) {
Same comment about using `object` as a type.

2022-05-23 22:23 UTC, LiamMartens commented on src/app/components/TokenButton/TokenButton.tsx
> +      setPluginValue(tokensInCompositionToken as SelectionValue);
Are we able to fix the typing error without type casting it?

2022-05-23 22:23 UTC, LiamMartens commented on src/app/components/SingleCompositionTokenForm.tsx
> +  setOrderObj: (newOrderObj: object) => void;
Same comment, please don't use `object` since it's too vague.

2022-05-25 05:43 UTC, six7 commented
I went over changes and I'll merge seeing as @LiamMartens comments have been addressed 👍

2022-05-25 05:44 UTC, merged