Support GHE URL structures for PR popup
six7/figma-tokens pull request #762
Opened 2022-05-26 15:37 UTC by zslabs

### Description

When using a custom base URL (GitHub Enterprise) as mentioned in https://github.com/six7/figma-tokens/issues/725 this new URL is not taken into account for the PR popup that appears when making changes. This PR adjusts the params to be object-based (I figured this way would break up the properties a bit cleaner) to support this and also updates the format of GitLab for consistency.

I started with `new URL()` but the string replace seemed like an easier way to start; as I'm unaware of all the different path segments a GHE URL can have.

There's also a few `// eslint-disable-next-line` additions as Husky was running up against these when I attempted to push and a https://eslint.org/docs/rules/no-case-declarations fix.

I didn't have a chance to fire this up in Figma, so another pair of 👀 would be appreciated. Let me know what you think!

2022-05-26 20:09 UTC, six7 commented
This is great! Do you mind basing changes on the `next` branch? We're keeping main the current release so we can ship hotfixes. Next is the branch we'll ship as the next major release and we had quite a few refactorings.

2022-05-26 20:26 UTC, zslabs commented
Sure thing! Let me know if the most recent commit looks better. Thanks!

2022-05-26 22:13 UTC, six7 requested changes
Just 3 comments about the eslint ignores. I know, it wasnt your code, but going forward we'd want to remove any eslint warnings by fixing them instead of ignoring them. 🙏

2022-05-26 22:13 UTC, six7 commented on src/app/components/PushDialog.tsx
> +          <form onSubmit={() => onConfirm(commitMessage, branch)}>
Can you change this to a useCallback and then remove the eslint ignore?

2022-05-26 22:13 UTC, six7 commented on src/app/components/PushDialog.tsx
> +                  // eslint-disable-next-line react/jsx-no-bind
Same here

2022-05-26 22:13 UTC, six7 commented on src/app/components/PushDialog.tsx
> +                  // eslint-disable-next-line react/jsx-no-bind
Same

2022-05-27 15:24 UTC, zslabs commented
Sure! New commit just pushed up.

2022-05-28 07:32 UTC, six7 commented
Currently still running into an error trying to build this (the `next` branch is type-safe and will fail on type errors), this line seems to offend as `id` doesn't exist for `LOCAL`: https://github.com/six7/figma-tokens/blob/62290a2828fc5f44add5bbde558f304706078c64/src/app/components/PushDialog.tsx#L22

2022-06-03 23:12 UTC, merged