add test for tokentooltipcontent
six7/figma-tokens pull request #792
Opened 2022-06-01 14:26 UTC by MightyDevKnight

2022-06-01 17:09 UTC, six7 requested changes
Can you also add some tests that cover the use of aliases? As in, we treat tooltips differently when a token contains an alias vs. one that doesn't (we show the resolved value as well as the raw value)

2022-06-02 05:12 UTC, MightyDevKnight commented on src/app/components/TokenTooltip/TokenTooltipContent.test.tsx
> +      name: 'typodgraphy.headlines.small',
Done

2022-06-02 05:12 UTC, MightyDevKnight commented on src/app/components/TokenTooltip/TokenTooltipContent.test.tsx
> +    expect(getByText('dropShadow') || getByText('innerShadow')).toBeInTheDocument();
Done

2022-06-02 14:38 UTC, six7 requested changes

2022-06-02 14:38 UTC, six7 commented on src/app/components/TokenTooltip/TokenTooltipContent.test.tsx
> +    name: 'border-radius.0',
This one has the same name as the previous one and has itself as an alias value?

2022-06-08 21:55 UTC, six7 commented on src/app/components/TokenTooltip/TokenTooltipContent.test.tsx
> +  it('tooltip test', () => {
this seems like it's all still work in progress? can you change this PRs status to be a Draft so that I know to not review it yet?

2022-06-13 08:25 UTC, closed without merging