Ft 237 token set tree
six7/figma-tokens pull request #838
Opened 2022-06-08 14:45 UTC by MightyDevKnight

2022-06-08 21:41 UTC, six7 requested changes

2022-06-08 21:41 UTC, six7 commented on src/app/components/TokenSetSelector.tsx
> +  console.log(allTokenSets);
```suggestion
```

2022-06-08 21:41 UTC, six7 commented on src/stories/TokenSetTree.stories.mdx
> +      'icon-button',
can you add nest a few of these files to become folders?

e.g. core/base, core/radii, core/colors and components/link, components/radio, ...

2022-06-09 05:04 UTC, MightyDevKnight commented on src/app/components/TokenSetSelector.tsx
> +  console.log(allTokenSets);
Done

2022-06-09 05:13 UTC, MightyDevKnight commented on src/stories/TokenSetTree.stories.mdx
> +      'icon-button',
Done

2022-06-09 05:49 UTC, six7 approved these changes

2022-06-09 05:49 UTC, merged