Ft 280 url sync provider gets duplicated on edit
six7/figma-tokens pull request #886
Opened 2022-06-15 14:57 UTC by MightyDevKnight

2022-06-15 20:59 UTC, six7 commented on src/app/components/Initiator.tsx
> +            dispatch.uiState.setAPIProviders(removeDuplicatedProviders(pluginMessage.providers));
i dont think we need to remove duplicated providers. we should rather not duplicate them in the first place.

2022-06-16 00:22 UTC, MightyDevKnight commented on src/app/components/Initiator.tsx
> +            dispatch.uiState.setAPIProviders(removeDuplicatedProviders(pluginMessage.providers));
You assigned this to @Hiroshi, right?

2022-06-16 03:57 UTC, six7 commented on src/app/components/Initiator.tsx
> +            dispatch.uiState.setAPIProviders(removeDuplicatedProviders(pluginMessage.providers));
Oh sorry, meant you. Was late for me 😅

2022-06-21 21:24 UTC, LiamMartens requested changes

2022-06-21 21:24 UTC, LiamMartens commented on src/app/components/StorageItemForm/URLForm.tsx
> +    if (!isNew) {
This logic seems a bit weird? What is the intention here? You are removing the old provider if the one you are editing is not new? Should we not just fix the issue where the actual provider is not updated? This feels like a monkey patch.

2022-06-30 21:07 UTC, six7 commented
Can you merge `next` in?

2022-07-01 07:41 UTC, closed without merging