Ft 301 gh multi file support for ado sync
six7/figma-tokens pull request #897
Opened 2022-06-16 13:28 UTC by swordEdge

2022-06-17 05:04 UTC, swordEdge commented on src/storage/ADOTokenStorage.ts
> +            const validationResult = await complexSingleFileSchema.safeParseAsync(res);
@LiamMartens In multifileSync, we send requests several times for each file.
And it is implemented using jsonFiles.map. And the response of this.getItem(path) is a single file, not multiFile.
That's why I used SingleFileSchema instead of multiFileSchema

2022-06-17 13:50 UTC, LiamMartens commented on src/storage/ADOTokenStorage.ts
> +            const validationResult = await complexSingleFileSchema.safeParseAsync(res);
I believe this should still be `multiFileSchema`. The single file validation schemas are for single file sync

2022-06-17 13:51 UTC, LiamMartens requested changes
Just the validation schema

2022-06-21 01:46 UTC, LiamMartens requested changes
Just one minor change - aside from that all good

2022-06-21 21:18 UTC, LiamMartens approved these changes

2022-06-22 05:37 UTC, merged