feat: coverage for adotokenstorage
six7/figma-tokens pull request #900
Opened 2022-06-16 16:00 UTC by LiamMartens

2022-06-17 12:45 UTC, six7 requested changes
One minor typo and one question for my understanding

2022-06-17 12:45 UTC, six7 commented on src/storage/ADOTokenStorage.ts
> +      // @REAMDE setting includeContent to true
```suggestion
      // @README setting includeContent to true
```

2022-06-17 12:45 UTC, six7 commented on src/storage/ADOTokenStorage.ts
> +            path: this.path,
So does this store $themes in the same file as the sets then? How did this even work before?

2022-06-19 16:08 UTC, LiamMartens commented on src/storage/ADOTokenStorage.ts
> +            path: this.path,
It does - it has to because of how the multifile was set-up from the beginning. It is based on the filename. It was not possible to change the file structure anymore since it had alreayd been set in a flat file structure.

2022-06-20 07:33 UTC, six7 approved these changes

2022-06-20 07:33 UTC, merged