fix issue with dulicating token-set-creates-a-new-blank-token-set
six7/figma-tokens pull request #906
Opened 2022-06-17 07:54 UTC by MightyDevKnight

2022-06-17 08:54 UTC, six7 commented on src/app/components/TokenSetSelector.tsx
> +  length: 0,
what is this one for?

2022-06-17 13:52 UTC, LiamMartens commented on src/app/store/models/tokenState.tsx
> -      return updateTokenSetsInState(state, null, [newName]);
Could you instead update the `updateTokenSetsInState` logic. It is necessary because it also updates the set names in the themes etc.. as we need to make sure they remain in sync.

2022-06-18 00:01 UTC, MightyDevKnight commented on src/app/components/TokenSetSelector.tsx
> +  length: 0,
There was an error with `eslint` and it fixes automatically to add length.
Removed.

2022-06-18 02:09 UTC, LiamMartens commented on src/app/store/models/tokenState.tsx
> +      return updateTokenSetsInState(newState, null);
Could you just remove your added logic and replace it with `return updateTokenSetsInState(state, null, [newName, state.tokens[name]]);`. This will have the same behavior and then we don't need to duplicate the logic.

2022-06-18 02:09 UTC, LiamMartens requested changes
Just 1 comment

2022-06-20 01:21 UTC, MightyDevKnight commented on src/app/store/models/tokenState.tsx
> +      return updateTokenSetsInState(newState, null);
Done.

2022-06-20 03:32 UTC, LiamMartens approved these changes

2022-06-20 07:15 UTC, merged