Ft 104 multi file sync handle set deletions
six7/figma-tokens pull request #915
Opened 2022-06-20 13:22 UTC by swordEdge

2022-06-21 21:44 UTC, LiamMartens requested changes

2022-06-21 21:44 UTC, LiamMartens commented on src/storage/schemas/multiFileSchema.ts
> +export const multiFileSchema = z.record(tokensMapSchema).or(z.array(z.object({
```suggestion
export const multiFileSchema = tokensMapSchema.or(z.array(z.object({
```

2022-06-28 01:23 UTC, LiamMartens commented
@swordEdge are we able to update the test coverage to pass?

2022-06-29 14:39 UTC, swordEdge commented
> @swordEdge are we able to update the test coverage to pass?

Modified test coverage for multi-file sync. I think it's still failing because of another unit test.

2022-06-29 21:09 UTC, LiamMartens commented
@swordEdge it's stil failing because `src/storage/GithubTokenStorage.ts` has a branch coverage diff of `-1`, maybe you can check which lines can be covered additionally?

2022-06-30 20:17 UTC, merged