Ft 103 add ability to import a local file json and a folder
six7/figma-tokens pull request #926
Opened 2022-06-23 17:10 UTC by swordEdge

2022-06-28 00:13 UTC, LiamMartens requested changes

2022-06-28 01:43 UTC, swordEdge commented on src/app/components/modals/PresetModal.tsx
> +              onClick={handleProviderClick(LoadProviderType.PRESET)}
If you see the definition of this function, you'll notice that this function doesn't be called on render.
It is only called when the user clicks the button.

2022-06-28 02:41 UTC, LiamMartens commented on src/app/components/modals/PresetModal.tsx
> +              onClick={handleProviderClick(LoadProviderType.PRESET)}
That's not correct - this will compile to something like this:
```
React.createElement(LoadProviderItem, {
  onClick: handleProviderClick(LoadProviderType.PRESET),
});
```
Here maybe you can more easily see the function is actually being executed during element creation;

I also created a Codepen to show this ([https://codepen.io/Liam9512/pen/LYdYPWd](https://codepen.io/Liam9512/pen/LYdYPWd)). You will notice you get the alert on load not when clicking the button.

You would need probably need to separate those callbacks or create separate components for these.

2022-06-29 01:03 UTC, LiamMartens approved these changes

2022-06-29 05:47 UTC, merged