multiselect implementation
six7/figma-tokens pull request #958
Opened 2022-07-01 11:52 UTC by fokkerone

### Add Multiselection for Contextmenu (Closes #245)
- 2 New TS Lint rules
- add DS_Store in .gitignore
- add Prettier as Formater, add some formating rules
- Solve LF/CRLF line ending problem for mdx stories
- Create 2 new exports in contextmenu and use these as alternative menu item in contextmenu

2022-07-02 18:37 UTC, six7 requested changes
Overall nice! some minor things. Also would love to get @LiamMartens review on this as well from a typescript perspective.

2022-07-02 18:37 UTC, six7 commented on .prettierrc
> +{
We already have a `.prettierrc.yml`, you can remove that

2022-07-02 18:37 UTC, six7 commented on src/app/components/MoreButton/MoreButton.tsx
> +        {/* <ContextMenuSeparator /> */}
This comment isn't needed, is it?

2022-07-02 18:37 UTC, six7 commented on src/app/components/MoreButton/MoreButtonPropertyMulti.tsx
> +  return (
This current implementation doesn't work by using up/down arrow keys. It seems to just skip those multi entries.

2022-07-02 18:37 UTC, six7 commented on .eslintrc.js
> +  extends: ["airbnb", "airbnb-typescript", "plugin:react-hooks/recommended"],
can you revert those changes? we dont use double quotes in our prettier config.

2022-07-04 07:20 UTC, fokkerone commented on .prettierrc
> +{
sorry forgot to delete after testing. will do!

2022-07-04 07:20 UTC, fokkerone commented on src/app/components/MoreButton/MoreButton.tsx
> +        {/* <ContextMenuSeparator /> */}
Nope

2022-07-04 07:21 UTC, fokkerone commented on src/app/components/MoreButton/MoreButtonPropertyMulti.tsx
> +  return (
ok, dont have this on my agenda. See what I can do to implement the default menu A11Y from radix on this one too

2022-07-04 07:22 UTC, fokkerone commented on .eslintrc.js
> +  extends: ["airbnb", "airbnb-typescript", "plugin:react-hooks/recommended"],
you haven´t a uniform style https://github.com/six7/figma-tokens/blob/main/.eslintrc.js
releates to .prettierrc

2022-07-08 12:18 UTC, LiamMartens requested changes
Just formatting

2022-07-08 12:18 UTC, LiamMartens commented on .eslintrc.js
> +  extends: ["airbnb", "airbnb-typescript", "plugin:react-hooks/recommended"],
I saw you added a `prettierrc` which is fine - but these should still change to single quotes I believe

2022-07-08 12:18 UTC, LiamMartens commented on src/stories/TokenButton.stories.mdx
> +import { store } from "@/app/store";
I guess these should also revert back to single quotes

2022-07-08 18:02 UTC, six7 commented
Closing this in favor of #969

2022-07-08 18:02 UTC, closed without merging