Ft 102 export add multiple files option
six7/figma-tokens pull request #965
Opened 2022-07-05 07:39 UTC by swordEdge

2022-07-06 11:22 UTC, six7 requested changes
Works great! Functional/design review done, would love it if Liam could take a look from a code perspective

2022-07-06 11:22 UTC, six7 commented on src/icons/file.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M2 0.5H2.5H9.5H9.70711L9.85355 0.646447L13.8536 4.64645L14 4.79289V5V15V15.5H13.5H2.5H2V15V1V0.5ZM3 1.5V14.5H13V5.5H9.5H9V5V1.5H3ZM10 2.20711L12.2929
```suggestion
<path fill-rule="evenodd" clip-rule="evenodd" d="M2 0.5H2.5H9.5H9.70711L9.85355 0.646447L13.8536 4.64645L14 4.79289V5V15V15.5H13.5H2.5H2V15V1V0.5ZM3 1.5V14.5H13V5.5H9.5H9V5V1.5H3ZM10 2.20711L12.2929 4.5H10V2.20711Z" fill="currentColor" />
```

2022-07-06 11:22 UTC, six7 commented on src/stitches.config.ts
> +      previewMaxHeight: '100px',
you don't have to use a token for that, it's only used once - there's no reusable value here

2022-07-06 11:22 UTC, six7 commented on src/app/components/ExportProvider/MultiFilesExport.tsx
> +            <Stack direction="row" gap={3} key={seed(index)}>
```suggestion
            <Stack direction="row" align="start" gap={3} key={seed(index)} css={{fontSize: '$xsmall'}}>
```

2022-07-06 11:22 UTC, six7 commented on src/app/components/ExportProvider/MultiFilesExport.tsx
> +      <Stack direction="column" gap={3} className="content scroll-container" css={{ maxHeight: '$previewMaxHeight' }}>
```suggestion
      <Stack direction="column" gap={3} className="content scroll-container" css={{ maxHeight: '200px' }}>
```

2022-07-08 12:14 UTC, LiamMartens requested changes

2022-07-08 12:14 UTC, LiamMartens commented on src/app/components/ExportProvider/SingleFileExport.tsx
> +        value={getFormattedTokens({
Let's `useMemo` this value; then we can also re-use it in the `Button` href

2022-07-12 23:54 UTC, LiamMartens approved these changes

2022-07-17 17:03 UTC, merged