feat: save token sort order in metadata
six7/figma-tokens pull request #985
Opened 2022-07-07 01:32 UTC by LiamMartens

This now includes the UI for sorting

2022-07-07 11:55 UTC, LiamMartens commented
Note to self: need fix coverage

2022-07-08 18:22 UTC, six7 requested changes
Getting `Error pushing to GitHub TypeError: Cannot read properties of undefined (reading 'forEach')` when trying to push changes to GitHub.

Also getting the same error for GitLab: `Error pushing to GitLab TypeError: Cannot read properties of undefined (reading 'forEach')`

And ADO: `Error pushing to ADO TypeError: Cannot read properties of undefined (reading 'forEach')`

2022-07-08 18:22 UTC, six7 commented on package.json
> +    "watch-js": "cross-env LAUNCHDARKLY_FLAGS=tokenThemes,gitBranchSelector,multiFileSync webpack --mode=development --watch",
Can we remove this? I'd rather have flags be license key dependent so we can test things as they are in the real world

2022-07-17 17:29 UTC, six7 approved these changes
Nice! 🎉

2022-07-17 17:34 UTC, merged