modify typography place holder
six7/figma-tokens pull request #992
Opened 2022-07-08 09:57 UTC by swordEdge

2022-07-08 12:07 UTC, LiamMartens approved these changes

2022-07-08 17:39 UTC, six7 requested changes

2022-07-08 17:39 UTC, six7 commented on src/app/components/SingleTypographyDownShiftInput.tsx
> +        name === 'color' ? `${name} #000000, hsla(), rgba() or {alias}` : `${name} value or {alias}`
```suggestion
        `${name} value or {alias}`
```

as we are in `SingleTypographyDownShiftInput.tsx` this is never going to be `color`. We can remove that check for `color`.

2022-07-13 02:48 UTC, LiamMartens approved these changes

2022-07-13 02:49 UTC, merged