Ft 51 ability to collapse expand token groups 564
six7/figma-tokens pull request #994
Opened 2022-07-08 13:43 UTC by MightyDevKnight

- [x] Functional review @six7

2022-07-17 17:18 UTC, six7 requested changes

2022-07-18 06:49 UTC, MightyDevKnight commented on src/app/components/TokenSetListOrTree/TokenSetListOrTree.tsx
> +                  <StyledFolderButtonChevronBox>
Done.

2022-07-19 08:03 UTC, six7 requested changes
I think tokensToTree is unused currently?

I added a bit of styling fixes. Functionality is approved!

2022-07-19 08:03 UTC, six7 commented on src/utils/tokensToTree.ts
> +import { SingleToken } from '@/types/tokens';
Where is that file used?

2022-07-25 01:19 UTC, six7 commented on src/utils/tokensToTree.ts
> +import { SingleToken } from '@/types/tokens';
@MightyDevKnight also make sure that test coverage isnt failing

2022-08-03 12:05 UTC, closed without merging